CONTINENTS = [
    ("Americas", "Americas"),
    ("Africa", "Africa"),
    ("Asia", "Asia"),
    ("Europe", "Europe"),
    ("Oceania", "Oceania"),
    ("Antarctica", "Antarctica"),
]

CURRENCIES = [
    ("EUR", "Euro"),
    ("AED", "UAE Dirham"),
    ("AFN", "Afghan Afghani"),
    ("ALL", "Albanian Lek"),
    ("AMD", "Armenian Dram"),
    ("ANG", "Netherlands Antilles Guilder"),
    ("AOA", "Angolan Kwanza"),
    ("ARS", "Argentine Peso"),
    ("AUD", "Australian Dollar"),
    ("AWG", "Aruban Florin"),
    ("AZN", "Azerbaijan Manat"),
    ("BAM", "Bosnian Mark"),
    ("BBD", "Barbados Dollar"),
    ("BDT", "Bangladeshi Taka"),
    ("BGN", "Bulgarian Lev"),
    ("BHD", "Bahraini Dinar"),
    ("BIF", "Burundi Franc"),
    ("BMD", "Bermudian Dollar"),
    ("BOB", "Boliviano"),
    ("BRL", "Brazilian Real"),
    ("BSD", "Bahamian Dollar"),
    ("BTN", "Bhutanese Ngultrum"),
    ("BWP", "Pula"),
    ("BYN", "Belarusian Ruble"),
    ("BZD", "Belize Dollar"),
    ("CAD", "Canadian Dollar"),
    ("CDF", "Franc Congolais"),
    ("CHF", "Swiss Franc"),
    ("CLP", "Chilean Peso"),
    ("CNY", "Renminbi (Yuan)"),
    ("COP", "Colombian Peso"),
    ("CRC", "Costa Rican Colón"),
    ("CSD", "Serbian Dinar"),
    ("CUP", "Cuban Peso"),
    ("CVE", "Cape Verde Escudo"),
    ("CZK", "Czech Koruna"),
    ("DJF", "Djibouti Franc"),
    ("DKK", "Danish Krone"),
    ("DOP", "Dominican Peso"),
    ("DZD", "Algerian Dinar"),
    ("EGP", "Egyptian Pound"),
    ("ERN", "Nakfa"),
    ("ETB", "Ethiopian Birr"),
    ("FJD", "Fiji Dollar"),
    ("FOK", "Faroese króna"),
    ("GBP", "Pound Sterling"),
    ("GEL", "Georgian Lari"),
    ("GHC", "Cedi"),
    ("GIP", "Gibraltar Pound"),
    ("GMD", "Dalasi"),
    ("GNF", "Guinea Franc"),
    ("GTQ", "Quetzal"),
    ("GWP", "Guinea-Bissau Peso"),
    ("GYD", "Guyana Dollar"),
    ("HKD", "Hong Kong Dollar"),
    ("HNL", "Lempira"),
    ("HTG", "Haitian Gourde"),
    ("HUF", "Hungarian Forint"),
    ("IDR", "Rupiah"),
    ("ILS", "New Israeli Sheqel"),
    ("INR", "Indian Rupee"),
    ("IQD", "Iraqi Dinar"),
    ("IRR", "Iranian Rial"),
    ("ISK", "Iceland Krona"),
    ("JMD", "Jamaican Dollar"),
    ("JOD", "Jordanian Dinar"),
    ("JPY", "Yen"),
    ("KES", "Kenyan Shilling"),
    ("KGS", "Som"),
    ("KHR", "Cambodian Riel"),
    ("KMF", "Comoro Franc"),
    ("KPW", "North Korean Won"),
    ("KRW", "Won"),
    ("KWD", "Kuwaiti Dinar"),
    ("KYD", "Cayman Islands Dollar"),
    ("KZT", "Tenge"),
    ("LBP", "Lebanese Pound"),
    ("LKR", "Sri Lanka Rupee"),
    ("LRD", "Liberian Dollar"),
    ("LSL", "Loti"),
    ("LYD", "Lybian Dinar"),
    ("MAD", "Moroccan Dirham"),
    ("MDL", "Moldovan Leu"),
    ("MGF", "Malagasy Franc"),
    ("MKD", "Macedonian Denar"),
    ("MMK", "Burmese Kyat"),
    ("MNT", "Mongolia Tughrik"),
    ("MOP", "Macanese Pataca"),
    ("MRO", "Ouguiya"),
    ("MTL", "Maltese Lira"),
    ("MUR", "Mauritius Rupee"),
    ("MVR", "Rufiyaa"),
    ("MWK", "Kwacha"),
    ("MXN", "Mexican Peso"),
    ("MYR", "Malaysian Ringgit"),
    ("MZM", "Mozambican Metical"),
    ("NAD", "Namibia Dollar"),
    ("NGN", "Nigerian Naira"),
    ("NIO", "Nicaraguan Córdoba"),
    ("NOK", "Norwegian Krone"),
    ("NPR", "Nepalese Rupee"),
    ("NZD", "New Zealand Dollar"),
    ("OMR", "Omani Rial"),
    ("PAB", "Panamanian Balboa"),
    ("PEN", "Peruvian Sol"),
    ("PGK", "Papua New Guinean Kina"),
    ("PHP", "Philippine Peso"),
    ("PKR", "Pakistan Rupee"),
    ("PLN", "Polish Zloty"),
    ("PYG", "Paraguayan Guarani"),
    ("QAR", "Qatari Rial"),
    ("RON", "Romanian Leu"),
    ("RSD", "Serbian Dinar"),
    ("RUB", "Russian Ruble"),
    ("RWF", "Rwanda Franc"),
    ("SAR", "Saudi Riyal"),
    ("SBD", "Solomon Islands Dollar"),
    ("SDG", "Sudanese Pound"),
    ("SEK", "Swedish Krona"),
    ("SGD", "Singapore Dollar"),
    ("SLL", "Leone"),
    ("SOS", "Somali Shilling"),
    ("SRG", "Suriname Guilder"),
    ("SVC", "Salvadoran Colón"),
    ("SZL", "Lilangeni"),
    ("THB", "Thai Baht"),
    ("TJS", "Somoni"),
    ("TMM", "Manat"),
    ("TND", "Tunisian Dinar"),
    ("TOP", "Pa'anga"),
    ("TRY", "Turkish Lira"),
    ("TTD", "Trinidad and Tobago Dollar"),
    ("TWD", "New Taiwan Dollar"),
    ("TZS", "Tanzanian Shilling"),
    ("UAH", "Ukrainian Hryvnia"),
    ("UGX", "Uganda Shilling"),
    ("USD", "US Dollar"),
    ("UYU", "Uruguayan Peso"),
    ("UZS", "Uzbekistan Sum"),
    ("VEF", "Venezuelan Bolívar"),
    ("VND", "Vietnamese Dong"),
    ("VUV", "Vanuatu Vatu"),
    ("WST", "Tala"),
    ("XAF", "Central African CFA franc"),
    ("XCD", "East Caribbean Dollar"),
    ("XOF", "CFA Franc BCEAO"),
    ("XPF", "South Pacific Franc"),
    ("YER", "Yemeni Rial"),
    ("ZAR", "South African Rand"),
    ("ZMW", "Zambian Kwacha"),
    ("ZWD", "Zimbabwe Dollar"),
]

LANGUAGES = [
    ("sq", "Albanian"),
    ("ar", "Arabic"),
    ("az", "Azerbaijani"),
    ("be", "Belarusian"),
    ("bs", "Bosnian"),
    ("bg", "Bulgarian"),
    ("hr", "Croatian"),
    ("cs", "Czech"),
    ("da", "Danish"),
    ("nl", "Dutch"),
    ("en", "English"),
    ("et", "Estonian"),
    ("fi", "Finnish"),
    ("fr", "French"),
    ("de", "German"),
    ("el", "Greek"),
    ("hu", "Hungarian"),
    ("is", "Icelandic"),
    ("it", "Italian"),
    ("lv", "Latvian"),
    ("lt", "Lithuanian"),
    ("lb", "Luxembourgish"),
    ("mk", "Macedonian"),
    ("mt", "Maltese"),
    ("cnr", "Montenegrin"),
    ("no", "Norwegian"),
    ("pl", "Polish"),
    ("pt", "Portuguese"),
    ("ro", "Romanian"),
    ("ru", "Russian"),
    ("sr", "Serbian"),
    ("sk", "Slovak"),
    ("sl", "Slovene"),
    ("es", "Spanish"),
    ("sv", "Swedish"),
    ("tr", "Turkish"),
    ("uk", "Ukrainian"),
]

lang_dict = {
    "Albanian": "sq",
    "Arabic": "ar",
    "Azerbaijani": "az",
    "Belarusian": "be",
    "Bosnian": "bs",
    "Bulgarian": "bg",
    "Croatian": "hr",
    "Czech": "cs",
    "Danish": "da",
    "Dutch": "nl",
    "English": "en",
    "Estonian": "et",
    "Finnish": "fi",
    "French": "fr",
    "German": "de",
    "Greek": "el",
    "Hungarian": "hu",
    "Icelandic": "is",
    "Italian": "it",
    "Latvian": "lv",
    "Lithuanian": "lt",
    "Luxembourgish": "lb",
    "Macedonian": "mk",
    "Maltese": "mt",
    "Montenegrin": "cnr",
    "Norwegian": "no",
    "Polish": "pl",
    "Portuguese": "pt",
    "Romanian": "ro",
    "Russian": "ru",
    "Serbian": "sr",
    "Slovak": "sk",
    "Slovene": "sl",
    "Spanish": "es",
    "Swedish": "sv",
    "Turkish": "tr",
    "Ukrainian": "uk",
}

countries_input = [
    {
        "name": "Afghanistan",
        "latitude": "33.93911",
        "longitude": "67.709953",
        "capital": "Kabul",
        "continent": "Asia",
        "currency_name": "Afghan Afghani",
        "currency_code": "AFN",
        "language": "Dari",
        "code": "93",
    },
    {
        "name": "Albania",
        "latitude": "41.153332",
        "longitude": "20.168331",
        "capital": "Tirana",
        "continent": "Europe",
        "currency_name": "Albanian Lek",
        "currency_code": "ALL",
        "language": "Albanian",
        "code": "355",
    },
    {
        "name": "Algeria",
        "latitude": "28.033886",
        "longitude": "1.659626",
        "capital": "Algiers",
        "continent": "Africa",
        "currency_name": "Algerian Dinar",
        "currency_code": "DZD",
        "language": "Arabic",
        "code": "213",
    },
    {
        "name": "Andorra",
        "latitude": "42.546245",
        "longitude": "1.601554",
        "capital": "Andorra la Vella",
        "continent": "Europe",
        "currency_name": "Euro",
        "currency_code": "EUR",
        "language": "Catalan",
        "code": "376",
    },
    {
        "name": "Angola",
        "latitude": "-11.202692",
        "longitude": "17.873887",
        "capital": "Luanda",
        "continent": "Africa",
        "currency_name": "Angolan Kwanza",
        "currency_code": "AOA",
        "language": "Portuguese",
        "code": "244",
    },
    {
        "name": "Anguilla",
        "latitude": "18.220554",
        "longitude": "-63.068615",
        "capital": "",
        "continent": "",
        "currency_name": "East Caribbean Dollar",
        "currency_code": "XCD",
        "language": "",
        "code": "1-264",
    },
    {
        "name": "Antarctica",
        "latitude": "-75.250973",
        "longitude": "-0.071389",
        "capital": "",
        "continent": "Antarctica",
        "currency_name": "",
        "currency_code": "",
        "language": "",
        "code": "672",
    },
    {
        "name": "Antigua and Barbuda",
        "latitude": "17.060816",
        "longitude": "-61.796428",
        "capital": "St. John's",
        "continent": "Americas",
        "currency_name": "East Caribbean Dollar",
        "currency_code": "XCD",
        "language": "English",
        "code": "1-268",
    },
    {
        "name": "Argentina",
        "latitude": "-38.416097",
        "longitude": "-63.616672",
        "capital": "Buenos Aires",
        "continent": "Americas",
        "currency_name": "Argentine Peso",
        "currency_code": "ARS",
        "language": "Spanish",
        "code": "54",
    },
    {
        "name": "Armenia",
        "latitude": "40.069099",
        "longitude": "45.038189",
        "capital": "Yerevan",
        "continent": "Asia",
        "currency_name": "Armenian Dram",
        "currency_code": "AMD",
        "language": "Armenian",
        "code": "374",
    },
    {
        "name": "Aruba",
        "latitude": "12.52111",
        "longitude": "-69.968338",
        "capital": "",
        "continent": "",
        "currency_name": "Aruban Florin",
        "currency_code": "AWG",
        "language": "",
        "code": "297",
    },
    {
        "name": "Australia",
        "latitude": "-25.274398",
        "longitude": "133.775136",
        "capital": "Canberra",
        "continent": "Oceania",
        "currency_name": "Australian Dollar",
        "currency_code": "AUD",
        "language": "English",
        "code": "61",
    },
    {
        "name": "Austria",
        "latitude": "47.516231",
        "longitude": "14.550072",
        "capital": "Vienna",
        "continent": "Europe",
        "currency_name": "Euro",
        "currency_code": "EUR",
        "language": "German",
        "code": "43",
    },
    {
        "name": "Azerbaijan",
        "latitude": "40.143105",
        "longitude": "47.576927",
        "capital": "Baku",
        "continent": "Asia",
        "currency_name": "Azerbaijan Manat",
        "currency_code": "AZN",
        "language": "Azerbaijani",
        "code": "994",
    },
    {
        "name": "Bahamas",
        "latitude": "25.03428",
        "longitude": "-77.39628",
        "capital": "Nassau",
        "continent": "Americas",
        "currency_name": "Bahamian Dollar",
        "currency_code": "BSD",
        "language": "",
        "code": "1-242",
    },
    {
        "name": "Bahrain",
        "latitude": "25.930414",
        "longitude": "50.637772",
        "capital": "Manama",
        "continent": "Asia",
        "currency_name": "Bahraini Dinar",
        "currency_code": "BHD",
        "language": "Arabic",
        "code": "973",
    },
    {
        "name": "Bangladesh",
        "latitude": "23.684994",
        "longitude": "90.356331",
        "capital": "Dhaka",
        "continent": "Asia",
        "currency_name": "Bangladeshi Taka",
        "currency_code": "BDT",
        "language": "Bangla",
        "code": "880",
    },
    {
        "name": "Barbados",
        "latitude": "13.193887",
        "longitude": "-59.543198",
        "capital": "Bridgetown",
        "continent": "Americas",
        "currency_name": "Barbados Dollar",
        "currency_code": "BBD",
        "language": "English",
        "code": "1-246",
    },
    {
        "name": "Belarus",
        "latitude": "53.709807",
        "longitude": "27.953389",
        "capital": "Minsk",
        "continent": "Europe",
        "currency_name": "Belarusian Ruble",
        "currency_code": "BYR",
        "language": "Belarusian",
        "code": "375",
    },
    {
        "name": "Belgium",
        "latitude": "50.503887",
        "longitude": "4.469936",
        "capital": "Brussels",
        "continent": "Europe",
        "currency_name": "Euro",
        "currency_code": "EUR",
        "language": "Dutch",
        "code": "32",
    },
    {
        "name": "Belize",
        "latitude": "17.189877",
        "longitude": "-88.49765",
        "capital": "Belmopan",
        "continent": "Americas",
        "currency_name": "Belize Dollar",
        "currency_code": "BZD",
        "language": "English",
        "code": "501",
    },
    {
        "name": "Benin",
        "latitude": "9.30769",
        "longitude": "2.315834",
        "capital": "Porto Novo",
        "continent": "Africa",
        "currency_name": "",
        "currency_code": "",
        "language": "French",
        "code": "229",
    },
    {
        "name": "Bermuda",
        "latitude": "32.321384",
        "longitude": "-64.75737",
        "capital": "",
        "continent": "",
        "currency_name": "Bermudian Dollar",
        "currency_code": "BMD",
        "language": "",
        "code": "1-441",
    },
    {
        "name": "Bhutan",
        "latitude": "27.514162",
        "longitude": "90.433601",
        "capital": "Thimphu",
        "continent": "Asia",
        "currency_name": "Bhutanese Ngultrum",
        "currency_code": "BTN",
        "language": "Dzongkha",
        "code": "975",
    },
    {
        "name": "Bolivia",
        "latitude": "-16.290154",
        "longitude": "-63.588653",
        "capital": "Sucre",
        "continent": "Americas",
        "currency_name": "Boliviano",
        "currency_code": "BOB",
        "language": "Spanish",
        "code": "591",
    },
    {
        "name": "Bosnia and Herzegovina",
        "latitude": "43.915886",
        "longitude": "17.679076",
        "capital": "Sarajevo",
        "continent": "Europe",
        "currency_name": "Convertible Mark",
        "currency_code": "BAM",
        "language": "Bosnian",
        "code": "387",
    },
    {
        "name": "Botswana",
        "latitude": "-22.328474",
        "longitude": "24.684866",
        "capital": "Gaborone",
        "continent": "Africa",
        "currency_name": "Pula",
        "currency_code": "BWP",
        "language": "English",
        "code": "267",
    },
    {
        "name": "Brazil",
        "latitude": "-14.235004",
        "longitude": "-51.92528",
        "capital": "Brasilia",
        "continent": "Americas",
        "currency_name": "Brazilian Real",
        "currency_code": "BRL",
        "language": "Portuguese",
        "code": "55",
    },
    {
        "name": "Brunei",
        "latitude": "4.535277",
        "longitude": "114.727669",
        "capital": "Bandar Seri Begawan",
        "continent": "Asia",
        "currency_name": "",
        "currency_code": "",
        "language": "Malay",
        "code": "673",
    },
    {
        "name": "Bulgaria",
        "latitude": "42.733883",
        "longitude": "25.48583",
        "capital": "Sofia",
        "continent": "Europe",
        "currency_name": "Bulgarian Lev",
        "currency_code": "BGN",
        "language": "Bulgarian",
        "code": "359",
    },
    {
        "name": "Burkina Faso",
        "latitude": "12.238333",
        "longitude": "-1.561593",
        "capital": "Ouagadougou",
        "continent": "Africa",
        "currency_name": "",
        "currency_code": "",
        "language": "French",
        "code": "226",
    },
    {
        "name": "Burundi",
        "latitude": "-3.373056",
        "longitude": "29.918886",
        "capital": "Bujumbura",
        "continent": "Africa",
        "currency_name": "Burundi Franc",
        "currency_code": "BIF",
        "language": "Kirundi",
        "code": "257",
    },
    {
        "name": "Cambodia",
        "latitude": "12.565679",
        "longitude": "104.990963",
        "capital": "Phnom Penh",
        "continent": "Asia",
        "currency_name": "Cambodian Riel",
        "currency_code": "KHR",
        "language": "Khmer",
        "code": "855",
    },
    {
        "name": "Cameroon",
        "latitude": "7.369722",
        "longitude": "12.354722",
        "capital": "Yaoundé",
        "continent": "Africa",
        "currency_name": "Central African CFA franc",
        "currency_code": "XAF",
        "language": "French",
        "code": "237",
    },
    {
        "name": "Canada",
        "latitude": "56.130366",
        "longitude": "-106.346771",
        "capital": "Ottawa",
        "continent": "Americas",
        "currency_name": "Canadian Dollar",
        "currency_code": "CAD",
        "language": "English",
        "code": "1",
    },
    {
        "name": "Cape Verde",
        "latitude": "16.002082",
        "longitude": "-24.013197",
        "capital": "Praia",
        "continent": "Africa",
        "currency_name": "Cape Verde Escudo",
        "currency_code": "CVE",
        "language": "Portuguese",
        "code": "238",
    },
    {
        "name": "Cayman Islands",
        "latitude": "19.513469",
        "longitude": "-80.566956",
        "capital": "",
        "continent": "",
        "currency_name": "Cayman Islands Dollar",
        "currency_code": "KYD",
        "language": "",
        "code": "1-345",
    },
    {
        "name": "Central African Republic",
        "latitude": "6.611111",
        "longitude": "20.939444",
        "capital": "Bangui",
        "continent": "Africa",
        "currency_name": "Central African CFA franc",
        "currency_code": "XAF",
        "language": "Sango",
        "code": "236",
    },
    {
        "name": "Chad",
        "latitude": "15.454166",
        "longitude": "18.732207",
        "capital": "N'Djamena",
        "continent": "Africa",
        "currency_name": "Central African CFA franc",
        "currency_code": "XAF",
        "language": "French",
        "code": "235",
    },
    {
        "name": "Chile",
        "latitude": "-35.675147",
        "longitude": "-71.542969",
        "capital": "Santiago",
        "continent": "Americas",
        "currency_name": "Chilean Peso",
        "currency_code": "CLP",
        "language": "Spanish",
        "code": "56",
    },
    {
        "name": "China",
        "latitude": "35.86166",
        "longitude": "104.195397",
        "capital": "Beijing",
        "continent": "Asia",
        "currency_name": "Renminbi (Yuan)",
        "currency_code": "CNY",
        "language": "Mandarin",
        "code": "86",
    },
    {
        "name": "Colombia",
        "latitude": "4.570868",
        "longitude": "-74.297333",
        "capital": "Bogota",
        "continent": "Americas",
        "currency_name": "Colombian Peso",
        "currency_code": "COP",
        "language": "Spanish",
        "code": "57",
    },
    {
        "name": "Comoros",
        "latitude": "-11.875001",
        "longitude": "43.872219",
        "capital": "Moroni",
        "continent": "Africa",
        "currency_name": "Comoro Franc",
        "currency_code": "KMF",
        "language": "Comorian",
        "code": "269",
    },
    {
        "name": "Democratic Republic of Congo",
        "latitude": "-4.038333",
        "longitude": "21.758664",
        "capital": "Kinshasa",
        "continent": "Africa",
        "currency_name": "Franc Congolais",
        "currency_code": "CDF",
        "language": "",
        "code": "",
    },
    {
        "name": "Republic of the Congo",
        "latitude": "-0.228021",
        "longitude": "15.827659",
        "capital": "Brazzaville",
        "continent": "Africa",
        "currency_name": "Central African CFA franc",
        "currency_code": "XAF",
        "language": "French",
        "code": "242",
    },
    {
        "name": "Costa Rica",
        "latitude": "9.748917",
        "longitude": "-83.753428",
        "capital": "San José",
        "continent": "Americas",
        "currency_name": "Costa Rican Colón",
        "currency_code": "CRC",
        "language": "Spanish",
        "code": "506",
    },
    {
        "name": "Ivory Coast",
        "latitude": "7.539989",
        "longitude": "-5.54708",
        "capital": "Yamoussoukro",
        "continent": "Africa",
        "currency_name": "CFA Franc BCEAO",
        "currency_code": "XOF",
        "language": "French",
        "code": "225",
    },
    {
        "name": "Croatia",
        "latitude": "45.1",
        "longitude": "15.2",
        "capital": "Zagreb",
        "continent": "Europe",
        "currency_name": "",
        "currency_code": "",
        "language": "Kuna",
        "code": "385",
    },
    {
        "name": "Cuba",
        "latitude": "21.521757",
        "longitude": "-77.781167",
        "capital": "Havana",
        "continent": "Americas",
        "currency_name": "Cuban Peso",
        "currency_code": "CUP",
        "language": "Spanish",
        "code": "53",
    },
    {
        "name": "Cyprus",
        "latitude": "35.126413",
        "longitude": "33.429859",
        "capital": "Nicosia",
        "continent": "Europe",
        "currency_name": "Euro",
        "currency_code": "EUR",
        "language": "Greek",
        "code": "357",
    },
    {
        "name": "Czech Republic",
        "latitude": "49.817492",
        "longitude": "15.472962",
        "capital": "Prague",
        "continent": "Europe",
        "currency_name": "Czech Koruna",
        "currency_code": "CZK",
        "language": "Czech",
        "code": "420",
    },
    {
        "name": "Denmark",
        "latitude": "56.26392",
        "longitude": "9.501785",
        "capital": "Copenagen",
        "continent": "Europe",
        "currency_name": "Danish Krone",
        "currency_code": "DKK",
        "language": "Danish",
        "code": "45",
    },
    {
        "name": "Djibouti",
        "latitude": "11.825138",
        "longitude": "42.590275",
        "capital": "Djibouti",
        "continent": "Africa",
        "currency_name": "Djibouti Franc",
        "currency_code": "DJF",
        "language": "Arabic",
        "code": "253",
    },
    {
        "name": "Dominica",
        "latitude": "15.414999",
        "longitude": "-61.370976",
        "capital": "Roseau",
        "continent": "Americas",
        "currency_name": "East Caribbean Dollar",
        "currency_code": "XCD",
        "language": "English",
        "code": "1-767",
    },
    {
        "name": "Dominican Republic",
        "latitude": "18.735693",
        "longitude": "-70.162651",
        "capital": "Santo Domingo",
        "continent": "Americas",
        "currency_name": "Dominican Peso",
        "currency_code": "DOP",
        "language": "Spanish",
        "code": "1-809",
    },
    {
        "name": "Ecuador",
        "latitude": "-1.831239",
        "longitude": "-78.183406",
        "capital": "Quito",
        "continent": "Americas",
        "currency_name": "US Dollar",
        "currency_code": "USD",
        "language": "Spanish",
        "code": "593",
    },
    {
        "name": "Egypt",
        "latitude": "26.820553",
        "longitude": "30.802498",
        "capital": "Cairo",
        "continent": "Africa",
        "currency_name": "Egyptian Pound",
        "currency_code": "EGP",
        "language": "Arabic",
        "code": "20",
    },
    {
        "name": "El Salvador",
        "latitude": "13.794185",
        "longitude": "-88.89653",
        "capital": "San Salvador",
        "continent": "Americas",
        "currency_name": "Salvadoran Colón",
        "currency_code": "SVC",
        "language": "Spanish",
        "code": "503",
    },
    {
        "name": "England",
        "latitude": "52.3555177",
        "longitude": "-1.1743197",
        "capital": "London",
        "continent": "Europe",
        "currency_name": "Pound Sterling",
        "currency_code": "GBP",
        "language": "English",
        "code": "44",
    },
    {
        "name": "Equatorial Guinea",
        "latitude": "1.650801",
        "longitude": "10.267895",
        "capital": "Malabo",
        "continent": "Africa",
        "currency_name": "Central African CFA franc",
        "currency_code": "XAF",
        "language": "Spanish",
        "code": "240",
    },
    {
        "name": "Eritrea",
        "latitude": "15.179384",
        "longitude": "39.782334",
        "capital": "Asmara",
        "continent": "Africa",
        "currency_name": "Nakfa",
        "currency_code": "ERN",
        "language": "Arabic",
        "code": "291",
    },
    {
        "name": "Estonia",
        "latitude": "58.595272",
        "longitude": "25.013607",
        "capital": "Tallinn",
        "continent": "Europe",
        "currency_name": "Euro",
        "currency_code": "EUR",
        "language": "Estonian",
        "code": "372",
    },
    {
        "name": "Ethiopia",
        "latitude": "9.145",
        "longitude": "40.489673",
        "capital": "Addis Ababa",
        "continent": "Africa",
        "currency_name": "Ethiopian Birr",
        "currency_code": "ETB",
        "language": "Amharic",
        "code": "251",
    },
    {
        "name": "Faroe Islands",
        "latitude": "61.892635",
        "longitude": "-6.911806",
        "capital": "",
        "continent": "",
        "currency_name": "Faroese króna",
        "currency_code": "FOK",
        "language": "",
        "code": "298",
    },
    {
        "name": "Fiji",
        "latitude": "-16.578193",
        "longitude": "179.414413",
        "capital": "Suva",
        "continent": "Oceania",
        "currency_name": "Fiji Dollar",
        "currency_code": "FJD",
        "language": "English",
        "code": "679",
    },
    {
        "name": "Finland",
        "latitude": "61.92411",
        "longitude": "25.748151",
        "capital": "Helsinki",
        "continent": "Europe",
        "currency_name": "Euro",
        "currency_code": "EUR",
        "language": "Finnish",
        "code": "358",
    },
    {
        "name": "France",
        "latitude": "46.227638",
        "longitude": "2.213749",
        "capital": "Paris",
        "continent": "Europe",
        "currency_name": "Euro",
        "currency_code": "EUR",
        "language": "French",
        "code": "33",
    },
    {
        "name": "French Guiana",
        "latitude": "3.933889",
        "longitude": "-53.125782",
        "capital": "",
        "continent": "",
        "currency_name": "Euro",
        "currency_code": "EUR",
        "language": "",
        "code": "",
    },
    {
        "name": "French Polynesia",
        "latitude": "-17.679742",
        "longitude": "-149.406843",
        "capital": "",
        "continent": "",
        "currency_name": "South Pacific Franc",
        "currency_code": "XPF",
        "language": "",
        "code": "689",
    },
    {
        "name": "Gabon",
        "latitude": "-0.803689",
        "longitude": "11.609444",
        "capital": "Libreville",
        "continent": "Africa",
        "currency_name": "Central African CFA franc",
        "currency_code": "XAF",
        "language": "French",
        "code": "241",
    },
    {
        "name": "Gambia",
        "latitude": "13.443182",
        "longitude": "-15.310139",
        "capital": "Banjul",
        "continent": "Africa",
        "currency_name": "Dalasi",
        "currency_code": "GMD",
        "language": "",
        "code": "220",
    },
    {
        "name": "Gaza Strip",
        "latitude": "31.354676",
        "longitude": "34.308825",
        "capital": "",
        "continent": "",
        "currency_name": "",
        "currency_code": "",
        "language": "",
        "code": "",
    },
    {
        "name": "Georgia",
        "latitude": "42.315407",
        "longitude": "43.356892",
        "capital": "Tbilisi",
        "continent": "Asia",
        "currency_name": "Lari",
        "currency_code": "GEL",
        "language": "Georgian",
        "code": "995",
    },
    {
        "name": "Germany",
        "latitude": "51.165691",
        "longitude": "10.451526",
        "capital": "Berlin",
        "continent": "Europe",
        "currency_name": "Euro",
        "currency_code": "EUR",
        "language": "German",
        "code": "49",
    },
    {
        "name": "Ghana",
        "latitude": "7.946527",
        "longitude": "-1.023194",
        "capital": "Accra",
        "continent": "Africa",
        "currency_name": "Cedi",
        "currency_code": "GHC",
        "language": "English",
        "code": "233",
    },
    {
        "name": "Gibraltar",
        "latitude": "36.137741",
        "longitude": "-5.345374",
        "capital": "",
        "continent": "",
        "currency_name": "Gibraltar Pound",
        "currency_code": "GIP",
        "language": "",
        "code": "350",
    },
    {
        "name": "Greece",
        "latitude": "39.074208",
        "longitude": "21.824312",
        "capital": "Athens",
        "continent": "Europe",
        "currency_name": "Euro",
        "currency_code": "EUR",
        "language": "Greek",
        "code": "30",
    },
    {
        "name": "Greenland",
        "latitude": "71.706936",
        "longitude": "-42.604303",
        "capital": "",
        "continent": "",
        "currency_name": "Danish Krone",
        "currency_code": "DKK",
        "language": "",
        "code": "299",
    },
    {
        "name": "Grenada",
        "latitude": "12.262776",
        "longitude": "-61.604171",
        "capital": "St. George's",
        "continent": "Americas",
        "currency_name": "East Caribbean Dollar",
        "currency_code": "XCD",
        "language": "English",
        "code": "1-473",
    },
    {
        "name": "Guadeloupe",
        "latitude": "16.995971",
        "longitude": "-62.067641",
        "capital": "",
        "continent": "",
        "currency_name": "Euro",
        "currency_code": "EUR",
        "language": "",
        "code": "",
    },
    {
        "name": "Guam",
        "latitude": "13.444304",
        "longitude": "144.793731",
        "capital": "",
        "continent": "",
        "currency_name": "US Dollar",
        "currency_code": "USD",
        "language": "",
        "code": "1-671",
    },
    {
        "name": "Guatemala",
        "latitude": "15.783471",
        "longitude": "-90.230759",
        "capital": "Guatemala City",
        "continent": "Americas",
        "currency_name": "Quetzal",
        "currency_code": "GTQ",
        "language": "Spanish",
        "code": "502",
    },
    {
        "name": "Guinea",
        "latitude": "9.945587",
        "longitude": "-9.696645",
        "capital": "Conakry",
        "continent": "Africa",
        "currency_name": "Guinea Franc",
        "currency_code": "GNF",
        "language": "French",
        "code": "224",
    },
    {
        "name": "Guinea-Bissau",
        "latitude": "11.803749",
        "longitude": "-15.180413",
        "capital": "Bissau",
        "continent": "Africa",
        "currency_name": "Guinea-Bissau Peso",
        "currency_code": "GWP",
        "language": "Portuguese",
        "code": "245",
    },
    {
        "name": "Guyana",
        "latitude": "4.860416",
        "longitude": "-58.93018",
        "capital": "Georgetown",
        "continent": "Americas",
        "currency_name": "Guyana Dollar",
        "currency_code": "GYD",
        "language": "English",
        "code": "592",
    },
    {
        "name": "Haiti",
        "latitude": "18.971187",
        "longitude": "-72.285215",
        "capital": "Port-au-Prince",
        "continent": "Americas",
        "currency_name": "Haitian Gourde",
        "currency_code": "HTG",
        "language": "Haitian Creole",
        "code": "509",
    },
    {
        "name": "Honduras",
        "latitude": "15.199999",
        "longitude": "-86.241905",
        "capital": "Tegucigalpa",
        "continent": "Americas",
        "currency_name": "Lempira",
        "currency_code": "HNL",
        "language": "Spanish",
        "code": "504",
    },
    {
        "name": "Hong Kong",
        "latitude": "22.396428",
        "longitude": "114.109497",
        "capital": "",
        "continent": "",
        "currency_name": "Hong Kong Dollar",
        "currency_code": "HKD",
        "language": "",
        "code": "852",
    },
    {
        "name": "Hungary",
        "latitude": "47.162494",
        "longitude": "19.503304",
        "capital": "Budapest",
        "continent": "Europe",
        "currency_name": "Forint",
        "currency_code": "HUF",
        "language": "Hungarian",
        "code": "36",
    },
    {
        "name": "Iceland",
        "latitude": "64.963051",
        "longitude": "-19.020835",
        "capital": "Reykjavík",
        "continent": "Europe",
        "currency_name": "Iceland Krona",
        "currency_code": "ISK",
        "language": "Icelandic",
        "code": "354",
    },
    {
        "name": "India",
        "latitude": "20.593684",
        "longitude": "78.96288",
        "capital": "New Delhi",
        "continent": "Asia",
        "currency_name": "Indian Rupee",
        "currency_code": "INR",
        "language": "Hindi",
        "code": "91",
    },
    {
        "name": "Indonesia",
        "latitude": "-0.789275",
        "longitude": "113.921327",
        "capital": "Jakarta",
        "continent": "Asia",
        "currency_name": "Rupiah",
        "currency_code": "IDR",
        "language": "Indonesian",
        "code": "62",
    },
    {
        "name": "Iran",
        "latitude": "32.427908",
        "longitude": "53.688046",
        "capital": "Tehran",
        "continent": "Asia",
        "currency_name": "Iranian Rial",
        "currency_code": "IRR",
        "language": "Persian",
        "code": "98",
    },
    {
        "name": "Iraq",
        "latitude": "33.223191",
        "longitude": "43.679291",
        "capital": "Baghdad",
        "continent": "Asia",
        "currency_name": "Iraqi Dinar",
        "currency_code": "IQD",
        "language": "Arabic",
        "code": "964",
    },
    {
        "name": "Ireland",
        "latitude": "53.41291",
        "longitude": "-8.24389",
        "capital": "Dublin",
        "continent": "Europe",
        "currency_name": "Euro",
        "currency_code": "EUR",
        "language": "English",
        "code": "353",
    },
    {
        "name": "Israel",
        "latitude": "31.046051",
        "longitude": "34.851612",
        "capital": "Jerusalem",
        "continent": "Asia",
        "currency_name": "New Israeli Sheqel",
        "currency_code": "ILS",
        "language": "Hebrew",
        "code": "972",
    },
    {
        "name": "Italy",
        "latitude": "41.87194",
        "longitude": "12.56738",
        "capital": "Rome",
        "continent": "Europe",
        "currency_name": "Euro",
        "currency_code": "EUR",
        "language": "Italian",
        "code": "39",
    },
    {
        "name": "Jamaica",
        "latitude": "18.109581",
        "longitude": "-77.297508",
        "capital": "Kingston",
        "continent": "Americas",
        "currency_name": "Jamaican Dollar",
        "currency_code": "JMD",
        "language": "English",
        "code": "1-876",
    },
    {
        "name": "Japan",
        "latitude": "36.204824",
        "longitude": "138.252924",
        "capital": "Tokyo",
        "continent": "Asia",
        "currency_name": "Yen",
        "currency_code": "JPY",
        "language": "Japanese",
        "code": "81",
    },
    {
        "name": "Jordan",
        "latitude": "30.585164",
        "longitude": "36.238414",
        "capital": "Amman",
        "continent": "Asia",
        "currency_name": "Jordanian Dinar",
        "currency_code": "JOD",
        "language": "Arabic",
        "code": "962",
    },
    {
        "name": "Kazakhstan",
        "latitude": "48.019573",
        "longitude": "66.923684",
        "capital": "Astana",
        "continent": "Asia",
        "currency_name": "Tenge",
        "currency_code": "KZT",
        "language": "Kazakh",
        "code": "7",
    },
    {
        "name": "Kenya",
        "latitude": "-0.023559",
        "longitude": "37.906193",
        "capital": "Nairobi",
        "continent": "Africa",
        "currency_name": "Kenyan Shilling",
        "currency_code": "KES",
        "language": "Swahili",
        "code": "254",
    },
    {
        "name": "Kiribati",
        "latitude": "-3.370417",
        "longitude": "-168.734039",
        "capital": "Tarawa",
        "continent": "Oceania",
        "currency_name": "Australian Dollar",
        "currency_code": "AUD",
        "language": "English",
        "code": "686",
    },
    {
        "name": "Kosovo",
        "latitude": "42.602636",
        "longitude": "20.902977",
        "capital": "Pristina",
        "continent": "Europe",
        "currency_name": "",
        "currency_code": "",
        "language": "Albanian",
        "code": "383",
    },
    {
        "name": "Kuwait",
        "latitude": "29.31166",
        "longitude": "47.481766",
        "capital": "Kuwait City",
        "continent": "Asia",
        "currency_name": "Kuwaiti Dinar",
        "currency_code": "KWD",
        "language": "Arabic",
        "code": "965",
    },
    {
        "name": "Kyrgyzstan",
        "latitude": "41.20438",
        "longitude": "74.766098",
        "capital": "Bishkek",
        "continent": "Asia",
        "currency_name": "Som",
        "currency_code": "KGS",
        "language": "Kyrgyz",
        "code": "996",
    },
    {
        "name": "Laos",
        "latitude": "19.85627",
        "longitude": "102.495496",
        "capital": "Vientiane",
        "continent": "Asia",
        "currency_name": "",
        "currency_code": "",
        "language": "Lao",
        "code": "856",
    },
    {
        "name": "Latvia",
        "latitude": "56.879635",
        "longitude": "24.603189",
        "capital": "Riga",
        "continent": "Europe",
        "currency_name": "Euro",
        "currency_code": "EUR",
        "language": "Latvian",
        "code": "371",
    },
    {
        "name": "Lebanon",
        "latitude": "33.854721",
        "longitude": "35.862285",
        "capital": "Beirut",
        "continent": "Asia",
        "currency_name": "Lebanese Pound",
        "currency_code": "LBP",
        "language": "Arabic",
        "code": "961",
    },
    {
        "name": "Lesotho",
        "latitude": "-29.609988",
        "longitude": "28.233608",
        "capital": "Maseru",
        "continent": "Africa",
        "currency_name": "Loti",
        "currency_code": "LSL",
        "language": "Sesotho",
        "code": "266",
    },
    {
        "name": "Liberia",
        "latitude": "6.428055",
        "longitude": "-9.429499",
        "capital": "Monrovia",
        "continent": "Africa",
        "currency_name": "Liberian Dollar",
        "currency_code": "LRD",
        "language": "English",
        "code": "231",
    },
    {
        "name": "Libya",
        "latitude": "26.3351",
        "longitude": "17.228331",
        "capital": "Tripoli",
        "continent": "Africa",
        "currency_name": "Lybian Dinar",
        "currency_code": "LYD",
        "language": "Arabic",
        "code": "218",
    },
    {
        "name": "Liechtenstein",
        "latitude": "47.166",
        "longitude": "9.555373",
        "capital": "Vaduz",
        "continent": "Europe",
        "currency_name": "Swiss Franc",
        "currency_code": "CHF",
        "language": "German",
        "code": "423",
    },
    {
        "name": "Lithuania",
        "latitude": "55.169438",
        "longitude": "23.881275",
        "capital": "Vilnius",
        "continent": "Europe",
        "currency_name": "Euro",
        "currency_code": "EUR",
        "language": "Lithuanian",
        "code": "370",
    },
    {
        "name": "Luxembourg",
        "latitude": "49.815273",
        "longitude": "6.129583",
        "capital": "Luxembourg",
        "continent": "Europe",
        "currency_name": "Euro",
        "currency_code": "EUR",
        "language": "German",
        "code": "352",
    },
    {
        "name": "Macau",
        "latitude": "22.198745",
        "longitude": "113.543873",
        "capital": "",
        "continent": "",
        "currency_name": "Macanese Pataca",
        "currency_code": "MOP",
        "language": "",
        "code": "853",
    },
    {
        "name": "Macedonia",
        "latitude": "41.608635",
        "longitude": "21.745275",
        "capital": "Skopje",
        "continent": "Europe",
        "currency_name": "Macedonian Denar",
        "currency_code": "MKD",
        "language": "Macedonian",
        "code": "389",
    },
    {
        "name": "Madagascar",
        "latitude": "-18.766947",
        "longitude": "46.869107",
        "capital": "Antananarivo",
        "continent": "Africa",
        "currency_name": "Malagasy Franc",
        "currency_code": "MGF",
        "language": "Malagasy",
        "code": "261",
    },
    {
        "name": "Malawi",
        "latitude": "-13.254308",
        "longitude": "34.301525",
        "capital": "Lilongwe",
        "continent": "Africa",
        "currency_name": "Kwacha",
        "currency_code": "MWK",
        "language": "English",
        "code": "265",
    },
    {
        "name": "Malaysia",
        "latitude": "4.210484",
        "longitude": "101.975766",
        "capital": "Kuala Lumpur",
        "continent": "Asia",
        "currency_name": "Malaysian Ringgit",
        "currency_code": "MYR",
        "language": "Malay",
        "code": "60",
    },
    {
        "name": "Maldives",
        "latitude": "3.202778",
        "longitude": "73.22068",
        "capital": "Malé",
        "continent": "Asia",
        "currency_name": "Rufiyaa",
        "currency_code": "MVR",
        "language": "Dhivehi",
        "code": "960",
    },
    {
        "name": "Mali",
        "latitude": "17.570692",
        "longitude": "-3.996166",
        "capital": "Bamako",
        "continent": "Africa",
        "currency_name": "CFA Franc BCEAO",
        "currency_code": "XOF",
        "language": "French",
        "code": "223",
    },
    {
        "name": "Malta",
        "latitude": "35.937496",
        "longitude": "14.375416",
        "capital": "Valletta",
        "continent": "Europe",
        "currency_name": "Maltese Lira",
        "currency_code": "MTL",
        "language": "Maltese",
        "code": "356",
    },
    {
        "name": "Martinique",
        "latitude": "14.641528",
        "longitude": "-61.024174",
        "capital": "",
        "continent": "",
        "currency_name": "Euro",
        "currency_code": "EUR",
        "language": "",
        "code": "",
    },
    {
        "name": "Mauritania",
        "latitude": "21.00789",
        "longitude": "-10.940835",
        "capital": "Nouakchott",
        "continent": "Africa",
        "currency_name": "Ouguiya",
        "currency_code": "MRO",
        "language": "Arabic",
        "code": "222",
    },
    {
        "name": "Mauritius",
        "latitude": "-20.348404",
        "longitude": "57.552152",
        "capital": "Port Louis",
        "continent": "Africa",
        "currency_name": "Mauritius Rupee",
        "currency_code": "MUR",
        "language": "English",
        "code": "230",
    },
    {
        "name": "Mayotte",
        "latitude": "-12.8275",
        "longitude": "45.166244",
        "capital": "",
        "continent": "",
        "currency_name": "",
        "currency_code": "",
        "language": "",
        "code": "262",
    },
    {
        "name": "Mexico",
        "latitude": "23.634501",
        "longitude": "-102.552784",
        "capital": "Mexico City",
        "continent": "Americas",
        "currency_name": "Mexican Peso",
        "currency_code": "MXN",
        "language": "Spanish",
        "code": "52",
    },
    {
        "name": "Micronesia",
        "latitude": "7.425554",
        "longitude": "150.550812",
        "capital": "Palikir",
        "continent": "Oceania",
        "currency_name": "US Dollar",
        "currency_code": "USD",
        "language": "English",
        "code": "691",
    },
    {
        "name": "Moldova",
        "latitude": "47.411631",
        "longitude": "28.369885",
        "capital": "Chisinau",
        "continent": "Europe",
        "currency_name": "Moldovan Leu",
        "currency_code": "MDL",
        "language": "Moldovan",
        "code": "373",
    },
    {
        "name": "Monaco",
        "latitude": "43.750298",
        "longitude": "7.412841",
        "capital": "Monaco",
        "continent": "Europe",
        "currency_name": "Euro",
        "currency_code": "EUR",
        "language": "French",
        "code": "377",
    },
    {
        "name": "Mongolia",
        "latitude": "46.862496",
        "longitude": "103.846656",
        "capital": "Ulaanbaatar",
        "continent": "Asia",
        "currency_name": "Mongolia Tughrik",
        "currency_code": "MNT",
        "language": "Mongolian",
        "code": "976",
    },
    {
        "name": "Montenegro",
        "latitude": "42.708678",
        "longitude": "19.37439",
        "capital": "Podgorica",
        "continent": "Europe",
        "currency_name": "Euro",
        "currency_code": "EUR",
        "language": "Montenegrin",
        "code": "382",
    },
    {
        "name": "Montserrat",
        "latitude": "16.742498",
        "longitude": "-62.187366",
        "capital": "",
        "continent": "",
        "currency_name": "East Caribbean Dollar",
        "currency_code": "XCD",
        "language": "",
        "code": "1-664",
    },
    {
        "name": "Morocco",
        "latitude": "31.791702",
        "longitude": "-7.09262",
        "capital": "Rabat",
        "continent": "Africa",
        "currency_name": "Moroccan Dirham",
        "currency_code": "MAD",
        "language": "Arabic",
        "code": "212",
    },
    {
        "name": "Mozambique",
        "latitude": "-18.665695",
        "longitude": "35.529562",
        "capital": "Maputo",
        "continent": "Africa",
        "currency_name": "Mozambican Metical",
        "currency_code": "MZM",
        "language": "Portuguese",
        "code": "258",
    },
    {
        "name": "Myanmar",
        "latitude": "21.913965",
        "longitude": "95.956223",
        "capital": "Naypyidaw",
        "continent": "Asia",
        "currency_name": "Burmese Kyat",
        "currency_code": "MMK",
        "language": "Burmese",
        "code": "95",
    },
    {
        "name": "Namibia",
        "latitude": "-22.95764",
        "longitude": "18.49041",
        "capital": "Windhoek",
        "continent": "Africa",
        "currency_name": "Namibia Dollar",
        "currency_code": "NAD",
        "language": "English",
        "code": "264",
    },
    {
        "name": "Nauru",
        "latitude": "-0.522778",
        "longitude": "166.931503",
        "capital": "Yaren",
        "continent": "Oceania",
        "currency_name": "Australian Dollar",
        "currency_code": "AUD",
        "language": "",
        "code": "674",
    },
    {
        "name": "Nepal",
        "latitude": "28.394857",
        "longitude": "84.124008",
        "capital": "Kathmandu",
        "continent": "Asia",
        "currency_name": "Nepalese Rupee",
        "currency_code": "NPR",
        "language": "Nepali",
        "code": "977",
    },
    {
        "name": "Netherlands",
        "latitude": "52.132633",
        "longitude": "5.291266",
        "capital": "Amsterdam",
        "continent": "Europe",
        "currency_name": "Euro",
        "currency_code": "EUR",
        "language": "Dutch",
        "code": "31",
    },
    {
        "name": "Netherlands Antilles",
        "latitude": "12.226079",
        "longitude": "-69.060087",
        "capital": "",
        "continent": "",
        "currency_name": "Netherlands Antilles Guilder",
        "currency_code": "ANG",
        "language": "",
        "code": "599",
    },
    {
        "name": "New Zealand",
        "latitude": "-40.900557",
        "longitude": "174.885971",
        "capital": "Wellington",
        "continent": "Oceania",
        "currency_name": "New Zealand Dollar",
        "currency_code": "NZD",
        "language": "English",
        "code": "64",
    },
    {
        "name": "Nicaragua",
        "latitude": "12.865416",
        "longitude": "-85.207229",
        "capital": "Managua",
        "continent": "Americas",
        "currency_name": "Nicaraguan Córdoba",
        "currency_code": "NIO",
        "language": "Spanish",
        "code": "505",
    },
    {
        "name": "Niger",
        "latitude": "17.607789",
        "longitude": "8.081666",
        "capital": "Niamey",
        "continent": "Africa",
        "currency_name": "West African CFA Franc",
        "currency_code": "XOF",
        "language": "French",
        "code": "227",
    },
    {
        "name": "Nigeria",
        "latitude": "9.081999",
        "longitude": "8.675277",
        "capital": "Abuja",
        "continent": "Africa",
        "currency_name": "Nigerian Naira",
        "currency_code": "NGN",
        "language": "English",
        "code": "234",
    },
    {
        "name": "Niue",
        "latitude": "-19.054445",
        "longitude": "-169.867233",
        "capital": "",
        "continent": "",
        "currency_name": "New Zealand Dollar",
        "currency_code": "NZD",
        "language": "",
        "code": "683",
    },
    {
        "name": "North Korea",
        "latitude": "40.339852",
        "longitude": "127.510093",
        "capital": "Pyongyang",
        "continent": "Asia",
        "currency_name": "North Korean Won",
        "currency_code": "KPW",
        "language": "Korean",
        "code": "850",
    },
    {
        "name": "Northern Ireland",
        "latitude": "54.7877149",
        "longitude": "-6.4923145",
        "capital": "Belfast",
        "continent": "Europe",
        "currency_name": "Pound Sterling",
        "currency_code": "GBP",
        "language": "English",
        "code": "44",
    },
    {
        "name": "Norway",
        "latitude": "60.472024",
        "longitude": "8.468946",
        "capital": "Oslo",
        "continent": "Europe",
        "currency_name": "Norwegian Krone",
        "currency_code": "NOK",
        "language": "Norwegian",
        "code": "47",
    },
    {
        "name": "Oman",
        "latitude": "21.512583",
        "longitude": "55.923255",
        "capital": "Muscat",
        "continent": "Asia",
        "currency_name": "Omani Rial",
        "currency_code": "OMR",
        "language": "Arabic",
        "code": "968",
    },
    {
        "name": "Pakistan",
        "latitude": "30.375321",
        "longitude": "69.345116",
        "capital": "Islamabad",
        "continent": "Asia",
        "currency_name": "Pakistan Rupee",
        "currency_code": "PKR",
        "language": "Urdu",
        "code": "92",
    },
    {
        "name": "Palau",
        "latitude": "7.51498",
        "longitude": "134.58252",
        "capital": "Melekeok",
        "continent": "Oceania",
        "currency_name": "US Dollar",
        "currency_code": "USD",
        "language": "English",
        "code": "680",
    },
    {
        "name": "Palestine",
        "latitude": "31.952162",
        "longitude": "35.233154",
        "capital": "East Jerusalem",
        "continent": "Asia",
        "currency_name": "",
        "currency_code": "",
        "language": "Arabic",
        "code": "970",
    },
    {
        "name": "Panama",
        "latitude": "8.537981",
        "longitude": "-80.782127",
        "capital": "Panama City",
        "continent": "Americas",
        "currency_name": "Panamanian Balboa",
        "currency_code": "PAB",
        "language": "Spanish",
        "code": "507",
    },
    {
        "name": "Papua New Guinea",
        "latitude": "-6.314993",
        "longitude": "143.95555",
        "capital": "Port Moresby",
        "continent": "Oceania",
        "currency_name": "Papua New Guinean Kina",
        "currency_code": "PGK",
        "language": "English",
        "code": "675",
    },
    {
        "name": "Paraguay",
        "latitude": "-23.442503",
        "longitude": "-58.443832",
        "capital": "Asunción",
        "continent": "Americas",
        "currency_name": "Paraguayan Guarani",
        "currency_code": "PYG",
        "language": "Spanish",
        "code": "595",
    },
    {
        "name": "Peru",
        "latitude": "-9.189967",
        "longitude": "-75.015152",
        "capital": "Lima",
        "continent": "Americas",
        "currency_name": "Peruvian Sol",
        "currency_code": "PEN",
        "language": "Spanish",
        "code": "51",
    },
    {
        "name": "Philippines",
        "latitude": "12.879721",
        "longitude": "121.774017",
        "capital": "Manila",
        "continent": "Asia",
        "currency_name": "Philippine Peso",
        "currency_code": "PHP",
        "language": "Filipino",
        "code": "63",
    },
    {
        "name": "Poland",
        "latitude": "51.919438",
        "longitude": "19.145136",
        "capital": "Warsaw",
        "continent": "Europe",
        "currency_name": "Polish Zloty",
        "currency_code": "PLN",
        "language": "Polish",
        "code": "48",
    },
    {
        "name": "Portugal",
        "latitude": "39.399872",
        "longitude": "-8.224454",
        "capital": "Lisbon",
        "continent": "Europe",
        "currency_name": "Euro",
        "currency_code": "EUR",
        "language": "Portuguese",
        "code": "351",
    },
    {
        "name": "Puerto Rico",
        "latitude": "18.220833",
        "longitude": "-66.590149",
        "capital": "",
        "continent": "",
        "currency_name": "US Dollar",
        "currency_code": "USD",
        "language": "",
        "code": "1-787",
    },
    {
        "name": "Qatar",
        "latitude": "25.354826",
        "longitude": "51.183884",
        "capital": "Doha",
        "continent": "Asia",
        "currency_name": "Qatari Rial",
        "currency_code": "QAR",
        "language": "Arabic",
        "code": "974",
    },
    {
        "name": "Réunion",
        "latitude": "-21.115141",
        "longitude": "55.536384",
        "capital": "",
        "continent": "",
        "currency_name": "",
        "currency_code": "",
        "language": "",
        "code": "",
    },
    {
        "name": "Romania",
        "latitude": "45.943161",
        "longitude": "24.96676",
        "capital": "Bucharest",
        "continent": "Europe",
        "currency_name": "Leu",
        "currency_code": "ROL",
        "language": "Romanian",
        "code": "40",
    },
    {
        "name": "Russia",
        "latitude": "61.52401",
        "longitude": "105.318756",
        "capital": "Moscow",
        "continent": "Europe",
        "currency_name": "Russian Ruble",
        "currency_code": "RUB",
        "language": "Romanian",
        "code": "7",
    },
    {
        "name": "Rwanda",
        "latitude": "-1.940278",
        "longitude": "29.873888",
        "capital": "Kigali",
        "continent": "Africa",
        "currency_name": "Rwanda Franc",
        "currency_code": "RWF",
        "language": "Russian",
        "code": "250",
    },
    {
        "name": "Saint Vincent and the Grenadines",
        "latitude": "12.984305",
        "longitude": "-61.287228",
        "capital": "Kingstown",
        "continent": "Americas",
        "currency_name": "East Caribbean Dollar",
        "currency_code": "XCD",
        "language": "English",
        "code": "1-784",
    },
    {
        "name": "Samoa",
        "latitude": "-13.759029",
        "longitude": "-172.104629",
        "capital": "Apia",
        "continent": "Oceania",
        "currency_name": "Tala",
        "currency_code": "WST",
        "language": "Samoan",
        "code": "685",
    },
    {
        "name": "San Marino",
        "latitude": "43.94236",
        "longitude": "12.457777",
        "capital": "San Marino",
        "continent": "Europe",
        "currency_name": "Euro",
        "currency_code": "EUR",
        "language": "Italian",
        "code": "378",
    },
    {
        "name": "São Tomé and Príncipe",
        "latitude": "0.18636",
        "longitude": "6.613081",
        "capital": "São Tomé",
        "continent": "Africa",
        "currency_name": "",
        "currency_code": "",
        "language": "",
        "code": "",
    },
    {
        "name": "Saudi Arabia",
        "latitude": "23.885942",
        "longitude": "45.079162",
        "capital": "Riyadh",
        "continent": "Asia",
        "currency_name": "Saudi Riyal",
        "currency_code": "SAR",
        "language": "Arabic",
        "code": "966",
    },
    {
        "name": "Scotland",
        "latitude": "56.4906712",
        "longitude": "-4.2026458",
        "capital": "Edinburgh",
        "continent": "Europe",
        "currency_name": "Pound Sterling",
        "currency_code": "GBP",
        "language": "English",
        "code": "44",
    },
    {
        "name": "Senegal",
        "latitude": "14.497401",
        "longitude": "-14.452362",
        "capital": "Dakar",
        "continent": "Africa",
        "currency_name": "CFA Franc BCEAO",
        "currency_code": "XOF",
        "language": "French",
        "code": "221",
    },
    {
        "name": "Serbia",
        "latitude": "44.016521",
        "longitude": "21.005859",
        "capital": "Belgrade",
        "continent": "Europe",
        "currency_name": "Serbian Dinar",
        "currency_code": "CSD",
        "language": "Serbian",
        "code": "381",
    },
    {
        "name": "Sierra Leone",
        "latitude": "8.460555",
        "longitude": "-11.779889",
        "capital": "Freetown",
        "continent": "Africa",
        "currency_name": "Leone",
        "currency_code": "SLL",
        "language": "English",
        "code": "232",
    },
    {
        "name": "Singapore",
        "latitude": "1.352083",
        "longitude": "103.819836",
        "capital": "Singapore",
        "continent": "Asia",
        "currency_name": "Singapore Dollar",
        "currency_code": "SGD",
        "language": "English",
        "code": "65",
    },
    {
        "name": "Slovakia",
        "latitude": "48.669026",
        "longitude": "19.699024",
        "capital": "Bratislava",
        "continent": "Europe",
        "currency_name": "",
        "currency_code": "",
        "language": "Slovak",
        "code": "421",
    },
    {
        "name": "Slovenia",
        "latitude": "46.151241",
        "longitude": "14.995463",
        "capital": "Ljubljana",
        "continent": "Europe",
        "currency_name": "Euro",
        "currency_code": "EUR",
        "language": "Slovene",
        "code": "386",
    },
    {
        "name": "Solomon Islands",
        "latitude": "-9.64571",
        "longitude": "160.156194",
        "capital": "Honiara",
        "continent": "Oceania",
        "currency_name": "Solomon Islands Dollar",
        "currency_code": "SBD",
        "language": "English",
        "code": "677",
    },
    {
        "name": "Somalia",
        "latitude": "5.152149",
        "longitude": "46.199616",
        "capital": "Mogadishu",
        "continent": "Africa",
        "currency_name": "Somali Shilling",
        "currency_code": "SOS",
        "language": "Somali Arabic",
        "code": "252",
    },
    {
        "name": "South Africa",
        "latitude": "-30.559482",
        "longitude": "22.937506",
        "capital": "Pretoria",
        "continent": "Africa",
        "currency_name": "Rand",
        "currency_code": "ZAR",
        "language": "Afrikaans",
        "code": "27",
    },
    {
        "name": "South Korea",
        "latitude": "35.907757",
        "longitude": "127.766922",
        "capital": "Seoul",
        "continent": "Asia",
        "currency_name": "Won",
        "currency_code": "KRW",
        "language": "Korean",
        "code": "82",
    },
    {
        "name": "Spain",
        "latitude": "40.463667",
        "longitude": "-3.74922",
        "capital": "Madrid",
        "continent": "Europe",
        "currency_name": "Euro",
        "currency_code": "EUR",
        "language": "Spanish",
        "code": "34",
    },
    {
        "name": "Sri Lanka",
        "latitude": "7.873054",
        "longitude": "80.771797",
        "capital": "Sri Jayawardenapura Kotte",
        "continent": "Asia",
        "currency_name": "Sri Lanka Rupee",
        "currency_code": "LKR",
        "language": "Sinhala",
        "code": "94",
    },
    {
        "name": "Sudan",
        "latitude": "12.862807",
        "longitude": "30.217636",
        "capital": "Khartoum",
        "continent": "Africa",
        "currency_name": "Sudanese Pound",
        "currency_code": "SDG",
        "language": "Arabic",
        "code": "249",
    },
    {
        "name": "Suriname",
        "latitude": "3.919305",
        "longitude": "-56.027783",
        "capital": "Paramaribo",
        "continent": "Americas",
        "currency_name": "Suriname Guilder",
        "currency_code": "SRG",
        "language": "Dutch",
        "code": "597",
    },
    {
        "name": "Swaziland",
        "latitude": "-26.522503",
        "longitude": "31.465866",
        "capital": "",
        "continent": "",
        "currency_name": "Lilangeni",
        "currency_code": "SZL",
        "language": "English",
        "code": "268",
    },
    {
        "name": "Sweden",
        "latitude": "60.128161",
        "longitude": "18.643501",
        "capital": "Stockholm",
        "continent": "Europe",
        "currency_name": "Swedish Krona",
        "currency_code": "SEK",
        "language": "Swedish",
        "code": "46",
    },
    {
        "name": "Switzerland",
        "latitude": "46.818188",
        "longitude": "8.227512",
        "capital": "Bern",
        "continent": "Europe",
        "currency_name": "Swiss Franc",
        "currency_code": "CHF",
        "language": "German",
        "code": "41",
    },
    {
        "name": "Syria",
        "latitude": "34.802075",
        "longitude": "38.996815",
        "capital": "Damascus",
        "continent": "Asia",
        "currency_name": "",
        "currency_code": "",
        "language": "Arabic",
        "code": "963",
    },
    {
        "name": "Taiwan",
        "latitude": "23.69781",
        "longitude": "120.960515",
        "capital": "Taipei",
        "continent": "Asia",
        "currency_name": "New Taiwan Dollar",
        "currency_code": "TWD",
        "language": "Chinese",
        "code": "886",
    },
    {
        "name": "Tajikistan",
        "latitude": "38.861034",
        "longitude": "71.276093",
        "capital": "Dushanbe",
        "continent": "Asia",
        "currency_name": "Somoni",
        "currency_code": "TJS",
        "language": "Tajik",
        "code": "992",
    },
    {
        "name": "Tanzania",
        "latitude": "-6.369028",
        "longitude": "34.888822",
        "capital": "Dodoma",
        "continent": "Africa",
        "currency_name": "Tanzanian Shilling",
        "currency_code": "TZS",
        "language": "Swahili",
        "code": "255",
    },
    {
        "name": "Thailand",
        "latitude": "15.870032",
        "longitude": "100.992541",
        "capital": "Bangkok",
        "continent": "Asia",
        "currency_name": "Thai Baht",
        "currency_code": "THB",
        "language": "Thai",
        "code": "66",
    },
    {
        "name": "Timor-Leste",
        "latitude": "-8.874217",
        "longitude": "125.727539",
        "capital": "",
        "continent": "",
        "currency_name": "",
        "currency_code": "",
        "language": "",
        "code": "",
    },
    {
        "name": "Togo",
        "latitude": "8.619543",
        "longitude": "0.824782",
        "capital": "Lomé",
        "continent": "Africa",
        "currency_name": "CFA Franc BCEAO",
        "currency_code": "XOF",
        "language": "French",
        "code": "228",
    },
    {
        "name": "Tonga",
        "latitude": "-21.178986",
        "longitude": "-175.198242",
        "capital": "Nukualofa",
        "continent": "Oceania",
        "currency_name": "Paʻanga",
        "currency_code": "TOP",
        "language": "English",
        "code": "676",
    },
    {
        "name": "Trinidad and Tobago",
        "latitude": "10.691803",
        "longitude": "-61.222503",
        "capital": "Port of Spain",
        "continent": "Americas",
        "currency_name": "Trinidad and Tobago Dollar",
        "currency_code": "TTD",
        "language": "English",
        "code": "1-868",
    },
    {
        "name": "Tunisia",
        "latitude": "33.886917",
        "longitude": "9.537499",
        "capital": "Tunis",
        "continent": "Africa",
        "currency_name": "Tunisian Dinar",
        "currency_code": "TND",
        "language": "Arabic",
        "code": "216",
    },
    {
        "name": "Turkey",
        "latitude": "38.963745",
        "longitude": "35.243322",
        "capital": "Ankara",
        "continent": "Asia",
        "currency_name": "Turkish Lira",
        "currency_code": "TRY",
        "language": "Turkish",
        "code": "90",
    },
    {
        "name": "Turkmenistan",
        "latitude": "38.969719",
        "longitude": "59.556278",
        "capital": "Ashgabat",
        "continent": "Asia",
        "currency_name": "Manat",
        "currency_code": "TMM",
        "language": "Turkmen",
        "code": "993",
    },
    {
        "name": "Tuvalu",
        "latitude": "-7.109535",
        "longitude": "177.64933",
        "capital": "Funafuti",
        "continent": "Oceania",
        "currency_name": "Australian Dollar",
        "currency_code": "AUD",
        "language": "Tuvaluan",
        "code": "688",
    },
    {
        "name": "Uganda",
        "latitude": "1.373333",
        "longitude": "32.290275",
        "capital": "Kampala",
        "continent": "Africa",
        "currency_name": "Uganda Shilling",
        "currency_code": "UGX",
        "language": "Swahili",
        "code": "256",
    },
    {
        "name": "Ukraine",
        "latitude": "48.379433",
        "longitude": "31.16558",
        "capital": "Kiev",
        "continent": "Europe",
        "currency_name": "Ukrainian Hryvnia",
        "currency_code": "UAH",
        "language": "Ukrainian",
        "code": "380",
    },
    {
        "name": "United Arab Emirates",
        "latitude": "23.424076",
        "longitude": "53.847818",
        "capital": "Abu Dhabi",
        "continent": "Asia",
        "currency_name": "UAE Dirham",
        "currency_code": "AED",
        "language": "Arabic",
        "code": "971",
    },
    {
        "name": "United States",
        "latitude": "37.09024",
        "longitude": "-95.712891",
        "capital": "Washington D.C.",
        "continent": "Americas",
        "currency_name": "US Dollar",
        "currency_code": "USD",
        "language": "English",
        "code": "1",
    },
    {
        "name": "Uruguay",
        "latitude": "-32.522779",
        "longitude": "-55.765835",
        "capital": "Montevideo",
        "continent": "Americas",
        "currency_name": "Uruguayan Peso",
        "currency_code": "UYU",
        "language": "Spanish",
        "code": "598",
    },
    {
        "name": "Uzbekistan",
        "latitude": "41.377491",
        "longitude": "64.585262",
        "capital": "Tashkent",
        "continent": "Asia",
        "currency_name": "Uzbekistan Sum",
        "currency_code": "UZS",
        "language": "Uzbek",
        "code": "998",
    },
    {
        "name": "Vanuatu",
        "latitude": "-15.376706",
        "longitude": "166.959158",
        "capital": "Port Vila",
        "continent": "Oceania",
        "currency_name": "Vanuatu Vatu",
        "currency_code": "VUV",
        "language": "Bislama",
        "code": "678",
    },
    {
        "name": "Venezuela",
        "latitude": "6.42375",
        "longitude": "-66.58973",
        "capital": "Caracas",
        "continent": "Americas",
        "currency_name": "Venezuelan Bolívar",
        "currency_code": "VEF",
        "language": "Spanish",
        "code": "58",
    },
    {
        "name": "Vietnam",
        "latitude": "14.058324",
        "longitude": "108.277199",
        "capital": "Hanoi",
        "continent": "Asia",
        "currency_name": "Vietnamese Dong",
        "currency_code": "VND",
        "language": "Vietnamese",
        "code": "84",
    },
    {
        "name": "Wales",
        "latitude": "52.1306607",
        "longitude": "-3.7837117",
        "capital": "Cardiff",
        "continent": "Europe",
        "currency_name": "Pound Sterling",
        "currency_code": "GBP",
        "language": "English",
        "code": "44",
    },
    {
        "name": "Western Sahara",
        "latitude": "24.215527",
        "longitude": "-12.885834",
        "capital": "",
        "continent": "",
        "currency_name": "Moroccan Dirham",
        "currency_code": "MAD",
        "language": "",
        "code": "212",
    },
    {
        "name": "Yemen",
        "latitude": "15.552727",
        "longitude": "48.516388",
        "capital": "Sana'a",
        "continent": "Asia",
        "currency_name": "Yemeni Rial",
        "currency_code": "YER",
        "language": "Arabic",
        "code": "967",
    },
    {
        "name": "Zambia",
        "latitude": "-13.133897",
        "longitude": "27.849332",
        "capital": "Lusaka",
        "continent": "Africa",
        "currency_name": "Zambian Kwacha",
        "currency_code": "ZMW",
        "language": "English",
        "code": "260",
    },
    {
        "name": "Zimbabwe",
        "latitude": "-19.015438",
        "longitude": "29.154857",
        "capital": "Harare",
        "continent": "Africa",
        "currency_name": "Zimbabwe Dollar",
        "currency_code": "ZWD",
        "language": "English",
        "code": "263",
    },
]
