CONTINENTS = [
    ("Americas", "Americas"),
    ("Africa", "Africa"),
    ("Asia", "Asia"),
    ("Europe", "Europe"),
    ("Oceania", "Oceania"),
    ("Antarctica", "Antarctica"),
]

CURRENCIES = [
    ("EUR", "Euro"),
    ("AED", "UAE Dirham"),
    ("AFN", "Afghan Afghani"),
    ("ALL", "Albanian Lek"),
    ("AMD", "Armenian Dram"),
    ("ANG", "Netherlands Antilles Guilder"),
    ("AOA", "Angolan Kwanza"),
    ("ARS", "Argentine Peso"),
    ("AUD", "Australian Dollar"),
    ("AWG", "Aruban Florin"),
    ("AZN", "Azerbaijan Manat"),
    ("BAM", "Bosnian Mark"),
    ("BBD", "Barbados Dollar"),
    ("BDT", "Bangladeshi Taka"),
    ("BGN", "Bulgarian Lev"),
    ("BHD", "Bahraini Dinar"),
    ("BIF", "Burundi Franc"),
    ("BMD", "Bermudian Dollar"),
    ("BOB", "Boliviano"),
    ("BRL", "Brazilian Real"),
    ("BSD", "Bahamian Dollar"),
    ("BTN", "Bhutanese Ngultrum"),
    ("BWP", "Pula"),
    ("BYN", "Belarusian Ruble"),
    ("BZD", "Belize Dollar"),
    ("CAD", "Canadian Dollar"),
    ("CDF", "Franc Congolais"),
    ("CHF", "Swiss Franc"),
    ("CLP", "Chilean Peso"),
    ("CNY", "Renminbi (Yuan)"),
    ("COP", "Colombian Peso"),
    ("CRC", "Costa Rican Colón"),
    ("CSD", "Serbian Dinar"),
    ("CUP", "Cuban Peso"),
    ("CVE", "Cape Verde Escudo"),
    ("CZK", "Czech Koruna"),
    ("DJF", "Djibouti Franc"),
    ("DKK", "Danish Krone"),
    ("DOP", "Dominican Peso"),
    ("DZD", "Algerian Dinar"),
    ("EGP", "Egyptian Pound"),
    ("ERN", "Nakfa"),
    ("ETB", "Ethiopian Birr"),
    ("FJD", "Fiji Dollar"),
    ("FOK", "Faroese króna"),
    ("GBP", "Pound Sterling"),
    ("GEL", "Georgian Lari"),
    ("GHC", "Cedi"),
    ("GIP", "Gibraltar Pound"),
    ("GMD", "Dalasi"),
    ("GNF", "Guinea Franc"),
    ("GTQ", "Quetzal"),
    ("GWP", "Guinea-Bissau Peso"),
    ("GYD", "Guyana Dollar"),
    ("HKD", "Hong Kong Dollar"),
    ("HNL", "Lempira"),
    ("HTG", "Haitian Gourde"),
    ("HUF", "Hungarian Forint"),
    ("IDR", "Rupiah"),
    ("ILS", "New Israeli Sheqel"),
    ("INR", "Indian Rupee"),
    ("IQD", "Iraqi Dinar"),
    ("IRR", "Iranian Rial"),
    ("ISK", "Iceland Krona"),
    ("JMD", "Jamaican Dollar"),
    ("JOD", "Jordanian Dinar"),
    ("JPY", "Yen"),
    ("KES", "Kenyan Shilling"),
    ("KGS", "Som"),
    ("KHR", "Cambodian Riel"),
    ("KMF", "Comoro Franc"),
    ("KPW", "North Korean Won"),
    ("KRW", "Won"),
    ("KWD", "Kuwaiti Dinar"),
    ("KYD", "Cayman Islands Dollar"),
    ("KZT", "Tenge"),
    ("LBP", "Lebanese Pound"),
    ("LKR", "Sri Lanka Rupee"),
    ("LRD", "Liberian Dollar"),
    ("LSL", "Loti"),
    ("LYD", "Lybian Dinar"),
    ("MAD", "Moroccan Dirham"),
    ("MDL", "Moldovan Leu"),
    ("MGF", "Malagasy Franc"),
    ("MKD", "Macedonian Denar"),
    ("MMK", "Burmese Kyat"),
    ("MNT", "Mongolia Tughrik"),
    ("MOP", "Macanese Pataca"),
    ("MRO", "Ouguiya"),
    ("MTL", "Maltese Lira"),
    ("MUR", "Mauritius Rupee"),
    ("MVR", "Rufiyaa"),
    ("MWK", "Kwacha"),
    ("MXN", "Mexican Peso"),
    ("MYR", "Malaysian Ringgit"),
    ("MZM", "Mozambican Metical"),
    ("NAD", "Namibia Dollar"),
    ("NGN", "Nigerian Naira"),
    ("NIO", "Nicaraguan Córdoba"),
    ("NOK", "Norwegian Krone"),
    ("NPR", "Nepalese Rupee"),
    ("NZD", "New Zealand Dollar"),
    ("OMR", "Omani Rial"),
    ("PAB", "Panamanian Balboa"),
    ("PEN", "Peruvian Sol"),
    ("PGK", "Papua New Guinean Kina"),
    ("PHP", "Philippine Peso"),
    ("PKR", "Pakistan Rupee"),
    ("PLN", "Polish Zloty"),
    ("PYG", "Paraguayan Guarani"),
    ("QAR", "Qatari Rial"),
    ("RON", "Romanian Leu"),
    ("RSD", "Serbian Dinar"),
    ("RUB", "Russian Ruble"),
    ("RWF", "Rwanda Franc"),
    ("SAR", "Saudi Riyal"),
    ("SBD", "Solomon Islands Dollar"),
    ("SDG", "Sudanese Pound"),
    ("SEK", "Swedish Krona"),
    ("SGD", "Singapore Dollar"),
    ("SLL", "Leone"),
    ("SOS", "Somali Shilling"),
    ("SRG", "Suriname Guilder"),
    ("SVC", "Salvadoran Colón"),
    ("SZL", "Lilangeni"),
    ("THB", "Thai Baht"),
    ("TJS", "Somoni"),
    ("TMM", "Manat"),
    ("TND", "Tunisian Dinar"),
    ("TOP", "Pa'anga"),
    ("TRY", "Turkish Lira"),
    ("TTD", "Trinidad and Tobago Dollar"),
    ("TWD", "New Taiwan Dollar"),
    ("TZS", "Tanzanian Shilling"),
    ("UAH", "Ukrainian Hryvnia"),
    ("UGX", "Uganda Shilling"),
    ("USD", "US Dollar"),
    ("UYU", "Uruguayan Peso"),
    ("UZS", "Uzbekistan Sum"),
    ("VEF", "Venezuelan Bolívar"),
    ("VND", "Vietnamese Dong"),
    ("VUV", "Vanuatu Vatu"),
    ("WST", "Tala"),
    ("XAF", "Central African CFA franc"),
    ("XCD", "East Caribbean Dollar"),
    ("XOF", "CFA Franc BCEAO"),
    ("XPF", "South Pacific Franc"),
    ("YER", "Yemeni Rial"),
    ("ZAR", "South African Rand"),
    ("ZMW", "Zambian Kwacha"),
    ("ZWD", "Zimbabwe Dollar"),
]

LANGUAGES = [
    ("sq", "Albanian"),
    ("ar", "Arabic"),
    ("az", "Azerbaijani"),
    ("be", "Belarusian"),
    ("bs", "Bosnian"),
    ("bg", "Bulgarian"),
    ("hr", "Croatian"),
    ("cs", "Czech"),
    ("da", "Danish"),
    ("nl", "Dutch"),
    ("en", "English"),
    ("et", "Estonian"),
    ("fi", "Finnish"),
    ("fr", "French"),
    ("de", "German"),
    ("el", "Greek"),
    ("ka", "Georgian"),
    ("hu", "Hungarian"),
    ("is", "Icelandic"),
    ("it", "Italian"),
    ("lv", "Latvian"),
    ("lt", "Lithuanian"),
    ("lb", "Luxembourgish"),
    ("mk", "Macedonian"),
    ("mt", "Maltese"),
    ("cnr", "Montenegrin"),
    ("no", "Norwegian"),
    ("pl", "Polish"),
    ("pt", "Portuguese"),
    ("ro", "Romanian"),
    ("ru", "Russian"),
    ("sr", "Serbian"),
    ("sk", "Slovak"),
    ("sl", "Slovene"),
    ("es", "Spanish"),
    ("sv", "Swedish"),
    ("tr", "Turkish"),
    ("uk", "Ukrainian"),
]

trips_stops = [
    {
        "city": "Orlando",
        "country": "Unites States",
        "arrival": "2006-12-08",
        "departure": "2007-03-02",
        "trip": "Orlando",
    },
    {
        "city": "Los Angeles",
        "country": "Unites States",
        "arrival": "2007-03-02",
        "departure": "2007-03-08",
        "trip": "LA",
    },
    {
        "city": "São Paulo",
        "country": "Brazil",
        "arrival": "2007-03-09",
        "departure": "2009-07-24",
        "trip": "",
    },
    {
        "city": "Rio de Janeiro",
        "country": "Brazil",
        "arrival": "2009-07-24",
        "departure": "2009-07-26",
        "trip": "Rio",
    },
]
trips_stops_2 = [
    {
        "city": "São Paulo",
        "country": "Brazil",
        "arrival": "2009-07-26",
        "departure": "2008-02-22",
        "trip": "",
    },
    {
        "city": "Peruíbe",
        "country": "Brazil",
        "arrival": "2008-02-22",
        "departure": "2008-02-24",
        "trip": "",
    },
    {
        "city": "São Paulo",
        "country": "Brazil",
        "arrival": "2008-02-24",
        "departure": "2009-03-27",
        "trip": "",
    },
    {
        "city": "Socorro",
        "country": "Brazil",
        "arrival": "2009-03-27",
        "departure": "2009-03-29",
        "trip": "",
    },
    {
        "city": "São Paulo",
        "country": "Brazil",
        "arrival": "2009-03-29",
        "departure": "2009-12-28",
        "trip": "",
    },
    {
        "city": "Ubatuba",
        "country": "Brazil",
        "arrival": "2009-12-28",
        "departure": "2010-01-03",
        "trip": "",
    },
    {
        "city": "São Paulo",
        "country": "Brazil",
        "arrival": "2010-01-03",
        "departure": "2010-03-05",
        "trip": "",
    },
    {
        "city": "Peruíbe",
        "country": "Brazil",
        "arrival": "2010-03-05",
        "departure": "2010-03-07",
        "trip": "",
    },
    {
        "city": "São Paulo",
        "country": "Brazil",
        "arrival": "2010-03-07",
        "departure": "2010-05-21",
        "trip": "",
    },
    {
        "city": "Guarujá",
        "country": "Brazil",
        "arrival": "2010-05-21",
        "departure": "2010-05-23",
        "trip": "",
    },
    {
        "city": "São Paulo",
        "country": "Brazil",
        "arrival": "2010-05-23",
        "departure": "2013-01-27",
        "trip": "",
    },
    {
        "city": "Guarujá",
        "country": "Brazil",
        "arrival": "2013-01-27",
        "departure": "2013-02-01",
        "trip": "",
    },
    {
        "city": "São Paulo",
        "country": "Brazil",
        "arrival": "2013-02-01",
        "departure": "2013-11-15",
        "trip": "",
    },
    {
        "city": "Guarujá",
        "country": "Brazil",
        "arrival": "2013-11-15",
        "departure": "2013-11-16",
        "trip": "",
    },
    {
        "city": "Itanhaém",
        "country": "Brazil",
        "arrival": "2013-11-16",
        "departure": "2013-11-17",
        "trip": "",
    },
    {
        "city": "São Paulo",
        "country": "Brazil",
        "arrival": "2013-11-17",
        "departure": "2013-11-19",
        "trip": "",
    },
    {
        "city": "Trindade",
        "country": "Brazil",
        "arrival": "2013-11-19",
        "departure": "2013-11-26",
        "trip": "Trindade",
    },
    {
        "city": "Paraty",
        "country": "Brazil",
        "arrival": "2013-11-21",
        "departure": "2013-11-21",
        "trip": "Trindade",
    },
    {
        "city": "São Paulo",
        "country": "Brazil",
        "arrival": "2013-11-21",
        "departure": "2014-04-29",
        "trip": "",
    },
    {
        "city": "Maceió",
        "country": "Brazil",
        "arrival": "2014-04-29",
        "departure": "2014-05-06",
        "trip": "Maceio",
    },
    {
        "city": "São Paulo",
        "country": "Brazil",
        "arrival": "2014-05-06",
        "departure": "2015-03-06",
        "trip": "",
    },
    {
        "city": "Dublin",
        "country": "Ireland",
        "arrival": "2015-03-06",
        "departure": "2015-04-03",
        "trip": "Dublin",
    },
    {
        "city": "London",
        "country": "England",
        "arrival": "2015-04-03",
        "departure": "2015-04-12",
        "trip": "London",
    },
    {
        "city": "Dublin",
        "country": "Ireland",
        "arrival": "2015-04-12",
        "departure": "2015-05-29",
        "trip": "Dublin",
    },
    {
        "city": "Brussels",
        "country": "Belgium",
        "arrival": "2015-05-29",
        "departure": "2015-06-02",
        "trip": "Rockabilly festival",
    },
    {
        "city": "Dublin",
        "country": "Ireland",
        "arrival": "2015-06-02",
        "departure": "2015-07-30",
        "trip": "Dublin",
    },
    {
        "city": "Copenhagen",
        "country": "Denmark",
        "arrival": "2015-07-30",
        "departure": "2015-08-01",
        "trip": "Denmark",
    },
    {
        "city": "Roskilde",
        "country": "Denmark",
        "arrival": "2015-08-01",
        "departure": "2015-08-01",
        "trip": "Denmark",
    },
    {
        "city": "Helsingør",
        "country": "Denmark",
        "arrival": "2015-08-02",
        "departure": "2015-08-04",
        "trip": "Denmark",
    },
    {
        "city": "Dublin",
        "country": "Ireland",
        "arrival": "2015-08-04",
        "departure": "2015-08-14",
        "trip": "Dublin",
    },
    {
        "city": "Glasgow",
        "country": "Scotland",
        "arrival": "2015-08-14",
        "departure": "2015-08-15",
        "trip": "Scotland",
    },
    {
        "city": "Inverness",
        "country": "Scotland",
        "arrival": "2015-08-15",
        "departure": "2015-08-16",
        "trip": "Scotland",
    },
    {
        "city": "Edinburgh",
        "country": "Scotland",
        "arrival": "2015-08-16",
        "departure": "2015-08-18",
        "trip": "Scotland",
    },
    {
        "city": "Dublin",
        "country": "Ireland",
        "arrival": "2015-08-18",
        "departure": "2015-08-22",
        "trip": "Dublin",
    },
    {
        "city": "London",
        "country": "England",
        "arrival": "2015-08-22",
        "departure": "2015-08-25",
        "trip": "London 2",
    },
    {
        "city": "Zurich",
        "country": "Switzerland",
        "arrival": "2015-08-25",
        "departure": "2015-08-27",
        "trip": "Swiss",
    },
    {
        "city": "Lucerne",
        "country": "Switzerland",
        "arrival": "2015-08-27",
        "departure": "2015-08-29",
        "trip": "Swiss",
    },
    {
        "city": "Interlaken",
        "country": "Switzerland",
        "arrival": "2015-08-29",
        "departure": "2015-08-31",
        "trip": "Swiss",
    },
    {
        "city": "Bern",
        "country": "Switzerland",
        "arrival": "2015-08-31",
        "departure": "2015-09-01",
        "trip": "Swiss",
    },
    {
        "city": "Dublin",
        "country": "Ireland",
        "arrival": "2015-09-01",
        "departure": "2015-12-17",
        "trip": "Dublin",
    },
    {
        "city": "Paris",
        "country": "France",
        "arrival": "2015-12-17",
        "departure": "2015-12-21",
        "trip": "Paris",
    },
    {
        "city": "Lisbon",
        "country": "Portugal",
        "arrival": "2015-12-21",
        "departure": "2015-12-24",
        "trip": "Christmas Portugal",
    },
    {
        "city": "Cascais",
        "country": "Portugal",
        "arrival": "2015-12-24",
        "departure": "2015-12-25",
        "trip": "Christmas Portugal",
    },
    {
        "city": "Lisbon",
        "country": "Portugal",
        "arrival": "2015-12-25",
        "departure": "2015-12-27",
        "trip": "Christmas Portugal",
    },
    {
        "city": "Berlin",
        "country": "Germany",
        "arrival": "2015-12-27",
        "departure": "2016-01-05",
        "trip": "New Year Berlin",
    },
    {
        "city": "Paris",
        "country": "France",
        "arrival": "2016-01-05",
        "departure": "2016-01-09",
        "trip": "France",
    },
    {
        "city": "Lyon",
        "country": "France",
        "arrival": "2016-01-09",
        "departure": "2016-01-24",
        "trip": "France",
    },
    {
        "city": "Helsinki",
        "country": "Finland",
        "arrival": "2016-01-24",
        "departure": "2016-01-26",
        "trip": "Lapland",
    },
    {
        "city": "Rovaniemi",
        "country": "Finland",
        "arrival": "2016-01-26",
        "departure": "2016-01-31",
        "trip": "Lapland",
    },
    {
        "city": "Lyon",
        "country": "France",
        "arrival": "2016-02-01",
        "departure": "2016-02-03",
        "trip": "France",
    },
    {
        "city": "Montpellier",
        "country": "France",
        "arrival": "2016-02-03",
        "departure": "2016-02-08",
        "trip": "France",
    },
    {
        "city": "Carcassonne",
        "country": "France",
        "arrival": "2016-02-08",
        "departure": "2016-02-09",
        "trip": "France",
    },
    {
        "city": "Toulouse",
        "country": "France",
        "arrival": "2016-02-09",
        "departure": "2016-02-11",
        "trip": "France",
    },
    {
        "city": "London",
        "country": "England",
        "arrival": "2016-02-12",
        "departure": "2016-02-16",
        "trip": "Back to Dublin",
    },
    {
        "city": "Edinburgh",
        "country": "Scotland",
        "arrival": "2016-02-17",
        "departure": "2016-02-18",
        "trip": "Back to Dublin",
    },
    {
        "city": "Dublin",
        "country": "Ireland",
        "arrival": "2016-02-18",
        "departure": "2016-02-29",
        "trip": "Back to Dublin",
    },
    {
        "city": "São Paulo",
        "country": "Brazil",
        "arrival": "2016-03-01",
        "departure": "2016-03-29",
        "trip": "",
    },
    {
        "city": "Berlin",
        "country": "Germany",
        "arrival": "2016-03-31",
        "departure": "2016-04-02",
        "trip": "",
    },
    {
        "city": "Milan",
        "country": "Italy",
        "arrival": "2016-04-02",
        "departure": "2016-04-04",
        "trip": "Italy road trip",
    },
    {
        "city": "Verona",
        "country": "Italy",
        "arrival": "2016-04-04",
        "departure": "2016-04-05",
        "trip": "Italy road trip",
    },
    {
        "city": "Venice",
        "country": "Italy",
        "arrival": "2016-04-05",
        "departure": "2016-04-05",
        "trip": "Italy road trip",
    },
    {
        "city": "Verona",
        "country": "Italy",
        "arrival": "2016-04-05",
        "departure": "2016-04-07",
        "trip": "Italy road trip",
    },
    {
        "city": "Florence",
        "country": "Italy",
        "arrival": "2016-04-07",
        "departure": "2016-04-08",
        "trip": "Italy road trip",
    },
    {
        "city": "Pisa",
        "country": "Italy",
        "arrival": "2016-04-08",
        "departure": "2016-04-08",
        "trip": "Italy road trip",
    },
    {
        "city": "Vinci",
        "country": "Italy",
        "arrival": "2016-04-08",
        "departure": "2016-04-08",
        "trip": "Italy road trip",
    },
    {
        "city": "San Gimignano",
        "country": "Italy",
        "arrival": "2016-04-09",
        "departure": "2016-04-09",
        "trip": "Italy road trip",
    },
    {
        "city": "Siena",
        "country": "Italy",
        "arrival": "2016-04-09",
        "departure": "2016-04-09",
        "trip": "Italy road trip",
    },
    {
        "city": "Florence",
        "country": "Italy",
        "arrival": "2016-04-09",
        "departure": "2016-04-11",
        "trip": "Italy road trip",
    },
    {
        "city": "Rome",
        "country": "Italy",
        "arrival": "2016-04-11",
        "departure": "2016-04-15",
        "trip": "Italy road trip",
    },
    {
        "city": "Vatican City",
        "country": "Vatican",
        "arrival": "2016-04-13",
        "departure": "2016-04-13",
        "trip": "Italy road trip",
    },
    {
        "city": "Athens",
        "country": "Greece",
        "arrival": "2016-04-16",
        "departure": "2016-04-18",
        "trip": "Greece",
    },
    {
        "city": "Rhodes",
        "country": "Greece",
        "arrival": "2016-04-18",
        "departure": "2016-04-19",
        "trip": "Greece",
    },
    {
        "city": "Lindos",
        "country": "Greece",
        "arrival": "2016-04-19",
        "departure": "2016-04-19",
        "trip": "Greece",
    },
    {
        "city": "Athens",
        "country": "Greece",
        "arrival": "2016-04-20",
        "departure": "2016-04-22",
        "trip": "Greece",
    },
    {
        "city": "Istanbul",
        "country": "Turkey",
        "arrival": "2016-04-22",
        "departure": "2016-04-24",
        "trip": "Turkey",
    },
    {
        "city": "Göreme",
        "country": "Turkey",
        "arrival": "2016-04-25",
        "departure": "2016-04-27",
        "trip": "Turkey",
    },
    {
        "city": "Istanbul",
        "country": "Turkey",
        "arrival": "2016-04-28",
        "departure": "2016-04-29",
        "trip": "Turkey",
    },
    {
        "city": "Cairo",
        "country": "Egypt",
        "arrival": "2016-04-29",
        "departure": "2016-05-02",
        "trip": "Egypt",
    },
    {
        "city": "Alexandria",
        "country": "Egypt",
        "arrival": "2016-05-02",
        "departure": "2016-05-03",
        "trip": "Egypt",
    },
    {
        "city": "Aswan",
        "country": "Egypt",
        "arrival": "2016-05-04",
        "departure": "2016-05-06",
        "trip": "Egypt",
    },
    {
        "city": "Luxor",
        "country": "Egypt",
        "arrival": "2016-05-06",
        "departure": "2016-05-09",
        "trip": "Egypt",
    },
    {
        "city": "Cairo",
        "country": "Egypt",
        "arrival": "2016-05-10",
        "departure": "2016-05-12",
        "trip": "Egypt",
    },
    {
        "city": "Haugesund",
        "country": "Norway",
        "arrival": "2016-05-13",
        "departure": "2016-05-16",
        "trip": "Norway 2016",
    },
    {
        "city": "Bergen",
        "country": "Norway",
        "arrival": "2016-05-16",
        "departure": "2016-05-17",
        "trip": "Norway 2016",
    },
    {
        "city": "Stavanger",
        "country": "Norway",
        "arrival": "2016-05-18",
        "departure": "2016-05-18",
        "trip": "Norway 2016",
    },
    {
        "city": "Marrakesh",
        "country": "Morocco",
        "arrival": "2016-05-19",
        "departure": "2016-05-22",
        "trip": "Morocco",
    },
    {
        "city": "Merzouga",
        "country": "Morocco",
        "arrival": "2016-05-22",
        "departure": "2016-05-23",
        "trip": "Morocco",
    },
    {
        "city": "London",
        "country": "England",
        "arrival": "2016-05-24",
        "departure": "2016-05-25",
        "trip": "Morocco",
    },
    {
        "city": "Sofia",
        "country": "Bulgaria",
        "arrival": "2016-05-25",
        "departure": "2016-05-30",
        "trip": "Bulgaria",
    },
    {
        "city": "Plovdiv",
        "country": "Bulgaria",
        "arrival": "2016-05-28",
        "departure": "2016-05-28",
        "trip": "Bulgaria",
    },
    {
        "city": "Veliko Tarnovo",
        "country": "Bulgaria",
        "arrival": "2016-05-30",
        "departure": "2016-06-03",
        "trip": "Bulgaria",
    },
    {
        "city": "Varna",
        "country": "Bulgaria",
        "arrival": "2016-06-03",
        "departure": "2016-06-06",
        "trip": "Bulgaria",
    },
    {
        "city": "Bucharest",
        "country": "Romania",
        "arrival": "2016-06-06",
        "departure": "2016-06-13",
        "trip": "Romania",
    },
    {
        "city": "Brasov",
        "country": "Romania",
        "arrival": "2016-06-13",
        "departure": "2016-06-16",
        "trip": "Romania",
    },
    {
        "city": "Budapest",
        "country": "Hungary",
        "arrival": "2016-06-17",
        "departure": "2016-06-21",
        "trip": "Hungary 2016",
    },
    {
        "city": "Vienna",
        "country": "Austria",
        "arrival": "2016-06-21",
        "departure": "2016-06-23",
        "trip": "Austria",
    },
    {
        "city": "Brno",
        "country": "Czech Republic",
        "arrival": "2016-06-24",
        "departure": "2016-06-25",
        "trip": "Czech 2016",
    },
    {
        "city": "Prague",
        "country": "Czech Republic",
        "arrival": "2016-06-25",
        "departure": "2016-06-28",
        "trip": "Czech 2016",
    },
    {
        "city": "Berlin",
        "country": "Germany",
        "arrival": "2016-06-28",
        "departure": "2016-07-02",
        "trip": "Berlin time",
    },
    {
        "city": "Lyon",
        "country": "France",
        "arrival": "2016-07-02",
        "departure": "2016-07-05",
        "trip": "Way to Spain",
    },
    {
        "city": "Barcelona",
        "country": "Spain",
        "arrival": "2016-07-06",
        "departure": "2016-07-09",
        "trip": "Way to Spain",
    },
    {
        "city": "Madrid",
        "country": "Spain",
        "arrival": "2016-07-09",
        "departure": "2016-07-13",
        "trip": "Way to Spain",
    },
    {
        "city": "Bilbao",
        "country": "Spain",
        "arrival": "2016-07-14",
        "departure": "2016-07-15",
        "trip": "Way to Spain",
    },
    {
        "city": "San Sebastian",
        "country": "Spain",
        "arrival": "2016-07-15",
        "departure": "2016-07-19",
        "trip": "Way to Spain",
    },
    {
        "city": "Salamanca",
        "country": "Spain",
        "arrival": "2016-07-19",
        "departure": "2016-07-20",
        "trip": "Way to Spain",
    },
    {
        "city": "Porto",
        "country": "Portugal",
        "arrival": "2016-07-20",
        "departure": "2016-07-22",
        "trip": "Porto",
    },
    {
        "city": "Delft",
        "country": "Netherlands",
        "arrival": "2016-07-22",
        "departure": "2016-07-25",
        "trip": "Netherland 2016",
    },
    {
        "city": "Rotterdam",
        "country": "Netherlands",
        "arrival": "2016-07-23",
        "departure": "2016-07-23",
        "trip": "Netherland 2017",
    },
    {
        "city": "The Hague",
        "country": "Netherlands",
        "arrival": "2016-07-24",
        "departure": "2016-07-24",
        "trip": "Netherland 2018",
    },
    {
        "city": "Amsterdam",
        "country": "Netherlands",
        "arrival": "2016-07-25",
        "departure": "2016-07-27",
        "trip": "Netherland 2019",
    },
    {
        "city": "Aachen",
        "country": "Germany",
        "arrival": "2016-07-27",
        "departure": "2016-07-29",
        "trip": "Berlin time",
    },
    {
        "city": "Berlin",
        "country": "Germany",
        "arrival": "2016-07-30",
        "departure": "2016-08-06",
        "trip": "Berlin time",
    },
    {
        "city": "Belgrade",
        "country": "Serbia",
        "arrival": "2016-08-07",
        "departure": "2016-08-14",
        "trip": "Serbia",
    },
    {
        "city": "Nis",
        "country": "Serbia",
        "arrival": "2016-08-14",
        "departure": "2016-08-15",
        "trip": "Serbia",
    },
    {
        "city": "Varna",
        "country": "Bulgaria",
        "arrival": "2016-08-16",
        "departure": "2016-08-25",
        "trip": "Bulgarian summer",
    },
    {
        "city": "Sunny Beach",
        "country": "Bulgaria",
        "arrival": "2016-08-26",
        "departure": "2016-08-28",
        "trip": "Bulgarian summer",
    },
    {
        "city": "Suceava",
        "country": "Romania",
        "arrival": "2016-08-29",
        "departure": "2016-08-30",
        "trip": "Ukraine",
    },
    {
        "city": "Kiev",
        "country": "Ukraine",
        "arrival": "2016-08-30",
        "departure": "2016-09-09",
        "trip": "Ukraine",
    },
    {
        "city": "Moscow",
        "country": "Russia",
        "arrival": "2016-09-10",
        "departure": "2016-09-17",
        "trip": "Russia",
    },
    {
        "city": "Saint Petersburg",
        "country": "Russia",
        "arrival": "2016-09-18",
        "departure": "2016-09-24",
        "trip": "Russia",
    },
    {
        "city": "Riga",
        "country": "Latvia",
        "arrival": "2016-09-25",
        "departure": "2016-09-27",
        "trip": "Latvia",
    },
    {
        "city": "Berlin",
        "country": "Germany",
        "arrival": "2016-09-27",
        "departure": "2016-09-29",
        "trip": "Berlin time",
    },
    {
        "city": "Aachen",
        "country": "Germany",
        "arrival": "2016-09-30",
        "departure": "2016-10-06",
        "trip": "Berlin time",
    },
    {
        "city": "Podgorica",
        "country": "Montenegro",
        "arrival": "2016-10-06",
        "departure": "2016-10-08",
        "trip": "Montenegro",
    },
    {
        "city": "Budva",
        "country": "Montenegro",
        "arrival": "2016-10-08",
        "departure": "2016-10-10",
        "trip": "Montenegro",
    },
    {
        "city": "Kotor",
        "country": "Montenegro",
        "arrival": "2016-10-10",
        "departure": "2016-10-14",
        "trip": "Montenegro",
    },
    {
        "city": "Dubrovnik",
        "country": "Croatia",
        "arrival": "2016-10-14",
        "departure": "2016-10-15",
        "trip": "Montenegro",
    },
    {
        "city": "Mostar",
        "country": "Bosnia and Herzegovina",
        "arrival": "2016-10-15",
        "departure": "2016-10-18",
        "trip": "Bosnia break",
    },
    {
        "city": "Sarajevo",
        "country": "Bosnia and Herzegovina",
        "arrival": "2016-10-18",
        "departure": "2016-11-26",
        "trip": "Bosnia break",
    },
    {
        "city": "Novi Sad",
        "country": "Serbia",
        "arrival": "2016-11-26",
        "departure": "2016-11-28",
        "trip": "Bosnia break",
    },
    {
        "city": "Brussels",
        "country": "Belgium",
        "arrival": "2016-11-29",
        "departure": "2016-12-01",
        "trip": "Bosnia break",
    },
    {
        "city": "Warsaw",
        "country": "Poland",
        "arrival": "2016-12-01",
        "departure": "2016-12-05",
        "trip": "Poland",
    },
    {
        "city": "Krakow",
        "country": "Poland",
        "arrival": "2016-12-05",
        "departure": "2016-12-18",
        "trip": "Poland",
    },
    {
        "city": "Munich",
        "country": "Germany",
        "arrival": "2016-12-19",
        "departure": "2017-01-10",
        "trip": "Holidays Munich",
    },
    {
        "city": "Berlin",
        "country": "Germany",
        "arrival": "2017-01-10",
        "departure": "2017-01-31",
        "trip": "Berlin time",
    },
    {
        "city": "Sofia",
        "country": "Bulgaria",
        "arrival": "2017-01-31",
        "departure": "2017-02-10",
        "trip": "Macedonia",
    },
    {
        "city": "Skopje",
        "country": "Macedonia",
        "arrival": "2017-02-10",
        "departure": "2017-02-24",
        "trip": "Macedonia",
    },
    {
        "city": "Krivogashtani",
        "country": "Macedonia",
        "arrival": "2017-02-24",
        "departure": "2017-02-25",
        "trip": "Macedonia",
    },
    {
        "city": "Krushevo",
        "country": "Macedonia",
        "arrival": "2017-02-25",
        "departure": "2017-02-25",
        "trip": "Macedonia",
    },
    {
        "city": "Prilep",
        "country": "Macedonia",
        "arrival": "2017-02-26",
        "departure": "2017-02-26",
        "trip": "Macedonia",
    },
    {
        "city": "Ohrid",
        "country": "Macedonia",
        "arrival": "2017-02-27",
        "departure": "2017-03-02",
        "trip": "Macedonia",
    },
    {
        "city": "Tirana",
        "country": "Albania",
        "arrival": "2017-03-02",
        "departure": "2017-04-09",
        "trip": "Albania",
    },
    {
        "city": "Durrës",
        "country": "Albania",
        "arrival": "2017-03-19",
        "departure": "2017-03-19",
        "trip": "Albania",
    },
    {
        "city": "Berat",
        "country": "Albania",
        "arrival": "2017-04-09",
        "departure": "2017-04-11",
        "trip": "Albania",
    },
    {
        "city": "Tirana",
        "country": "Albania",
        "arrival": "2017-04-11",
        "departure": "2017-04-18",
        "trip": "Albania",
    },
    {
        "city": "Sarandë",
        "country": "Albania",
        "arrival": "2017-04-18",
        "departure": "2017-04-20",
        "trip": "Albania",
    },
    {
        "city": "Gjirokastër",
        "country": "Albania",
        "arrival": "2017-04-20",
        "departure": "2017-04-23",
        "trip": "Albania",
    },
    {
        "city": "Thessaloniki",
        "country": "Greece",
        "arrival": "2017-04-24",
        "departure": "2017-04-27",
        "trip": "Thessaloniki",
    },
    {
        "city": "Berlin",
        "country": "Germany",
        "arrival": "2017-04-27",
        "departure": "2017-05-06",
        "trip": "Berlin time",
    },
    {
        "city": "Aachen",
        "country": "Germany",
        "arrival": "2017-05-06",
        "departure": "2017-05-07",
        "trip": "Berlin time",
    },
    {
        "city": "São Paulo",
        "country": "Brazil",
        "arrival": "2017-05-09",
        "departure": "2017-10-13",
        "trip": "",
    },
    {
        "city": "Ilhabela",
        "country": "Brazil",
        "arrival": "2017-10-13",
        "departure": "2017-10-15",
        "trip": "Camp-a-billy",
    },
    {
        "city": "São Paulo",
        "country": "Brazil",
        "arrival": "2017-10-15",
        "departure": "2018-05-15",
        "trip": "",
    },
    {
        "city": "Bertioga",
        "country": "Brazil",
        "arrival": "2018-01-10",
        "departure": "2018-01-10",
        "trip": "Bate-volta Debs",
    },
    {
        "city": "Rio de Janeiro",
        "country": "Brazil",
        "arrival": "2018-05-15",
        "departure": "2018-05-17",
        "trip": "Rio Raisa",
    },
    {
        "city": "Campo Grande",
        "country": "Brazil",
        "arrival": "2018-05-17",
        "departure": "2018-05-21",
        "trip": "Debs",
    },
    {
        "city": "São Paulo",
        "country": "Brazil",
        "arrival": "2018-05-21",
        "departure": "2018-05-24",
        "trip": "",
    },
    {
        "city": "Berlin",
        "country": "Germany",
        "arrival": "2018-05-26",
        "departure": "2018-05-27",
        "trip": "",
    },
    {
        "city": "Manchester",
        "country": "England",
        "arrival": "2018-05-27",
        "departure": "2018-05-27",
        "trip": "Nicole",
    },
    {
        "city": "Liverpool",
        "country": "England",
        "arrival": "2018-05-27",
        "departure": "2018-05-29",
        "trip": "Nicole",
    },
    {
        "city": "London",
        "country": "England",
        "arrival": "2018-05-29",
        "departure": "2018-05-30",
        "trip": "Nicole",
    },
    {
        "city": "Berlin",
        "country": "Germany",
        "arrival": "2018-05-30",
        "departure": "2018-06-22",
        "trip": "",
    },
    {
        "city": "Porto",
        "country": "Portugal",
        "arrival": "2018-06-22",
        "departure": "2018-06-24",
        "trip": "São João",
    },
    {
        "city": "Berlin",
        "country": "Germany",
        "arrival": "2018-06-24",
        "departure": "2018-09-07",
        "trip": "",
    },
    {
        "city": "Barcelona",
        "country": "Spain",
        "arrival": "2018-09-07",
        "departure": "2018-09-09",
        "trip": "Palma",
    },
    {
        "city": "Palma de Mallorca",
        "country": "Spain",
        "arrival": "2018-09-09",
        "departure": "2018-09-12",
        "trip": "Palma",
    },
    {
        "city": "Berlin",
        "country": "Germany",
        "arrival": "2018-09-12",
        "departure": "2018-09-21",
        "trip": "",
    },
    {
        "city": "Munich",
        "country": "Germany",
        "arrival": "2018-09-21",
        "departure": "2018-09-23",
        "trip": "Oktoberfest",
    },
    {
        "city": "Berlin",
        "country": "Germany",
        "arrival": "2018-09-23",
        "departure": "2018-11-09",
        "trip": "",
    },
    {
        "city": "Prague",
        "country": "Czech Republic",
        "arrival": "2018-11-09",
        "departure": "2018-11-11",
        "trip": "Blues",
    },
    {
        "city": "Berlin",
        "country": "Germany",
        "arrival": "2018-11-11",
        "departure": "2018-11-23",
        "trip": "",
    },
    {
        "city": "Aachen",
        "country": "Germany",
        "arrival": "2018-11-23",
        "departure": "2018-11-25",
        "trip": "Emily",
    },
    {
        "city": "Berlin",
        "country": "Germany",
        "arrival": "2018-11-25",
        "departure": "2019-01-24",
        "trip": "",
    },
    {
        "city": "Telnice",
        "country": "Czech Republic",
        "arrival": "2019-01-24",
        "departure": "2019-01-25",
        "trip": "Ski 1",
    },
    {
        "city": "Telč",
        "country": "Czech Republic",
        "arrival": "2019-01-26",
        "departure": "2019-01-27",
        "trip": "Ski 1",
    },
    {
        "city": "Berlin",
        "country": "Germany",
        "arrival": "2019-01-27",
        "departure": "2019-03-01",
        "trip": "",
    },
    {
        "city": "Prague",
        "country": "Czech Republic",
        "arrival": "2019-03-01",
        "departure": "2019-03-03",
        "trip": "Blues",
    },
    {
        "city": "Berlin",
        "country": "Germany",
        "arrival": "2019-03-03",
        "departure": "2019-03-22",
        "trip": "",
    },
    {
        "city": "Copenhagen",
        "country": "Denmark",
        "arrival": "2019-03-22",
        "departure": "2019-03-24",
        "trip": "Blues",
    },
    {
        "city": "Berlin",
        "country": "Germany",
        "arrival": "2019-03-24",
        "departure": "2019-04-20",
        "trip": "",
    },
    {
        "city": "São Paulo",
        "country": "Brazil",
        "arrival": "2019-04-21",
        "departure": "2019-05-03",
        "trip": "",
    },
    {
        "city": "Berlin",
        "country": "Germany",
        "arrival": "2019-05-04",
        "departure": "2019-05-17",
        "trip": "",
    },
    {
        "city": "Paris",
        "country": "France",
        "arrival": "2019-05-17",
        "departure": "2019-05-19",
        "trip": "Blues",
    },
    {
        "city": "Berlin",
        "country": "Germany",
        "arrival": "2019-05-19",
        "departure": "2019-05-25",
        "trip": "",
    },
    {
        "city": "Cologne",
        "country": "Germany",
        "arrival": "2019-05-25",
        "departure": "2019-05-26",
        "trip": "Poliamigos",
    },
    {
        "city": "Düsseldorf",
        "country": "Germany",
        "arrival": "2019-05-26",
        "departure": "2019-05-26",
        "trip": "Poliamigos",
    },
    {
        "city": "Berlin",
        "country": "Germany",
        "arrival": "2019-05-26",
        "departure": "2019-05-30",
        "trip": "",
    },
    {
        "city": "Stockholm",
        "country": "Sweden",
        "arrival": "2019-05-30",
        "departure": "2019-05-31",
        "trip": "Sweden",
    },
    {
        "city": "Gothenburg",
        "country": "Sweden",
        "arrival": "2019-06-01",
        "departure": "2019-06-02",
        "trip": "Sweden",
    },
    {
        "city": "Berlin",
        "country": "Germany",
        "arrival": "2019-06-02",
        "departure": "2019-06-08",
        "trip": "",
    },
    {
        "city": "Luxembourg",
        "country": "Luxembourg",
        "arrival": "2019-06-08",
        "departure": "2019-06-10",
        "trip": "Luxembourg",
    },
    {
        "city": "Berlin",
        "country": "Germany",
        "arrival": "2019-06-10",
        "departure": "2019-06-14",
        "trip": "",
    },
    {
        "city": "Tbilisi",
        "country": "Georgia",
        "arrival": "2019-06-14",
        "departure": "2019-06-15",
        "trip": "Georgia",
    },
    {
        "city": "Kazbegi",
        "country": "Georgia",
        "arrival": "2019-06-15",
        "departure": "2019-06-16",
        "trip": "Georgia",
    },
    {
        "city": "Batumi",
        "country": "Georgia",
        "arrival": "2019-06-16",
        "departure": "2019-06-18",
        "trip": "Georgia",
    },
    {
        "city": "Berlin",
        "country": "Germany",
        "arrival": "2019-06-18",
        "departure": "2019-07-20",
        "trip": "",
    },
    {
        "city": "Warsaw",
        "country": "Poland",
        "arrival": "2019-07-20",
        "departure": "2019-07-22",
        "trip": "CS Poland",
    },
    {
        "city": "Berlin",
        "country": "Germany",
        "arrival": "2019-07-22",
        "departure": "2019-08-23",
        "trip": "",
    },
    {
        "city": "Dublin",
        "country": "Ireland",
        "arrival": "2019-08-23",
        "departure": "2019-08-25",
        "trip": "Back to Ireland",
    },
    {
        "city": "Belfast",
        "country": "Northern Ireland",
        "arrival": "2019-08-25",
        "departure": "2019-08-25",
        "trip": "Back to Ireland",
    },
    {
        "city": "Berlin",
        "country": "Germany",
        "arrival": "2019-08-25",
        "departure": "2019-08-30",
        "trip": "",
    },
    {
        "city": "Oslo",
        "country": "Norway",
        "arrival": "2019-08-30",
        "departure": "2019-09-01",
        "trip": "Forro fest",
    },
    {
        "city": "Berlin",
        "country": "Germany",
        "arrival": "2019-09-01",
        "departure": "2019-09-13",
        "trip": "",
    },
    {
        "city": "Bari",
        "country": "Italy",
        "arrival": "2019-09-13",
        "departure": "2019-09-14",
        "trip": "Italy beach",
    },
    {
        "city": "Polignano a Mare",
        "country": "Italy",
        "arrival": "2019-09-14",
        "departure": "2019-09-14",
        "trip": "Italy beach",
    },
    {
        "city": "Napoli",
        "country": "Italy",
        "arrival": "2019-09-15",
        "departure": "2019-09-17",
        "trip": "Italy beach",
    },
    {
        "city": "Pompei",
        "country": "Italy",
        "arrival": "2019-09-17",
        "departure": "2019-09-17",
        "trip": "Italy beach",
    },
    {
        "city": "Berlin",
        "country": "Germany",
        "arrival": "2019-09-17",
        "departure": "2019-09-28",
        "trip": "",
    },
    {
        "city": "Reykjavík",
        "country": "Iceland",
        "arrival": "2019-09-28",
        "departure": "2019-10-05",
        "trip": "Iceland",
    },
    {
        "city": "Kalfafellsstadur",
        "country": "Iceland",
        "arrival": "2019-10-05",
        "departure": "2019-10-06",
        "trip": "Iceland",
    },
    {
        "city": "Berlin",
        "country": "Germany",
        "arrival": "2019-10-06",
        "departure": "2019-10-11",
        "trip": "",
    },
    {
        "city": "Athens",
        "country": "Greece",
        "arrival": "2019-10-11",
        "departure": "2019-10-14",
        "trip": "Blues",
    },
    {
        "city": "Berlin",
        "country": "Germany",
        "arrival": "2019-10-14",
        "departure": "2019-12-24",
        "trip": "",
    },
    {
        "city": "Merida",
        "country": "Mexico",
        "arrival": "2019-12-24",
        "departure": "2019-12-26",
        "trip": "Mayan riviera",
    },
    {
        "city": "Tulum",
        "country": "Mexico",
        "arrival": "2019-12-26",
        "departure": "2019-12-27",
        "trip": "Mayan riviera",
    },
    {
        "city": "Akumal",
        "country": "Mexico",
        "arrival": "2019-12-27",
        "departure": "2019-12-29",
        "trip": "Mayan riviera",
    },
    {
        "city": "Playa del Carmen",
        "country": "Mexico",
        "arrival": "2019-12-29",
        "departure": "2019-12-31",
        "trip": "Mayan riviera",
    },
    {
        "city": "Holbox",
        "country": "Mexico",
        "arrival": "2019-12-31",
        "departure": "2020-01-01",
        "trip": "Mayan riviera",
    },
    {
        "city": "Merida",
        "country": "Mexico",
        "arrival": "2020-01-01",
        "departure": "2020-01-02",
        "trip": "Mayan riviera",
    },
    {
        "city": "Berlin",
        "country": "Germany",
        "arrival": "2020-01-03",
        "departure": "2020-02-21",
        "trip": "",
    },
    {
        "city": "Haugesund",
        "country": "Norway",
        "arrival": "2020-02-21",
        "departure": "2020-02-23",
        "trip": "Haugesund 2020",
    },
    {
        "city": "Berlin",
        "country": "Germany",
        "arrival": "2020-02-23",
        "departure": "2020-07-04",
        "trip": "",
    },
    {
        "city": "Dresden",
        "country": "Germany",
        "arrival": "2020-07-04",
        "departure": "2020-07-06",
        "trip": "Sexy Schweiz",
    },
    {
        "city": "Berlin",
        "country": "Germany",
        "arrival": "2020-07-06",
        "departure": "2021-03-04",
        "trip": "",
    },
    {
        "city": "São Paulo",
        "country": "Brazil",
        "arrival": "2021-03-05",
        "departure": "2021-03-11",
        "trip": "",
    },
    {
        "city": "Chapada dos Guimarães",
        "country": "Brazil",
        "arrival": "2021-03-11",
        "departure": "2021-03-15",
        "trip": "Chapada",
    },
    {
        "city": "São Paulo",
        "country": "Brazil",
        "arrival": "2021-03-15",
        "departure": "2021-03-17",
        "trip": "",
    },
    {
        "city": "Caraguatatuba",
        "country": "Brazil",
        "arrival": "2021-03-17",
        "departure": "2021-03-19",
        "trip": "",
    },
    {
        "city": "São Paulo",
        "country": "Brazil",
        "arrival": "2021-03-19",
        "departure": "2021-04-11",
        "trip": "",
    },
    {
        "city": "Berlin",
        "country": "Germany",
        "arrival": "2021-04-11",
        "departure": "2021-06-24",
        "trip": "",
    },
    {
        "city": "Sardegna",
        "country": "Italy",
        "arrival": "2021-06-25",
        "departure": "2021-06-27",
        "trip": "Sardegna",
    },
    {
        "city": "Sardegna",
        "country": "Italy",
        "arrival": "2021-06-27",
        "departure": "2021-06-29",
        "trip": "Sardegna",
    },
    {
        "city": "Sardegna",
        "country": "Italy",
        "arrival": "2021-06-29",
        "departure": "2021-06-30",
        "trip": "Sardegna",
    },
    {
        "city": "Berlin",
        "country": "Germany",
        "arrival": "2021-06-30",
        "departure": "2021-09-18",
        "trip": "",
    },
    {
        "city": "Tallinn",
        "country": "Estonia",
        "arrival": "2021-09-18",
        "departure": "2021-09-21",
        "trip": "Estonia",
    },
    {
        "city": "Berlin",
        "country": "Germany",
        "arrival": "2021-09-21",
        "departure": "2021-10-02",
        "trip": "",
    },
    {
        "city": "Pirna",
        "country": "Germany",
        "arrival": "2021-10-02",
        "departure": "2021-10-03",
        "trip": "Sexy Schweiz 2",
    },
    {
        "city": "Berlin",
        "country": "Germany",
        "arrival": "2021-10-03",
        "departure": "2021-10-19",
        "trip": "",
    },
    {
        "city": "Paris",
        "country": "France",
        "arrival": "2021-10-19",
        "departure": "2021-10-20",
        "trip": "Guadeloupe",
    },
    {
        "city": "Grande-Terre",
        "country": "Guadeloupe",
        "arrival": "2021-10-21",
        "departure": "2021-10-23",
        "trip": "Guadeloupe",
    },
    {
        "city": "Basse-Terre",
        "country": "Guadeloupe",
        "arrival": "2021-10-23",
        "departure": "2021-10-25",
        "trip": "Guadeloupe",
    },
    {
        "city": "Les Saintes",
        "country": "Guadeloupe",
        "arrival": "2021-10-25",
        "departure": "2021-10-26",
        "trip": "Guadeloupe",
    },
    {
        "city": "Basse-Terre",
        "country": "Guadeloupe",
        "arrival": "2021-10-26",
        "departure": "2021-10-28",
        "trip": "Guadeloupe",
    },
    {
        "city": "Marie-Galante",
        "country": "Guadeloupe",
        "arrival": "2021-10-28",
        "departure": "2021-10-31",
        "trip": "Guadeloupe",
    },
    {
        "city": "Basse-Terre",
        "country": "Guadeloupe",
        "arrival": "2021-10-31",
        "departure": "2021-11-02",
        "trip": "Guadeloupe",
    },
    {
        "city": "Grande-Terre",
        "country": "Guadeloupe",
        "arrival": "2021-11-02",
        "departure": "2021-11-04",
        "trip": "Guadeloupe",
    },
    {
        "city": "Berlin",
        "country": "Germany",
        "arrival": "2021-11-04",
        "departure": "2021-12-09",
        "trip": "",
    },
    {
        "city": "Lisbon",
        "country": "Portugal",
        "arrival": "2021-12-09",
        "departure": "2021-12-13",
        "trip": "Forro fest",
    },
    {
        "city": "Seville",
        "country": "Spain",
        "arrival": "2021-12-14",
        "departure": "2021-12-17",
        "trip": "Andalusia",
    },
    {
        "city": "Granada",
        "country": "Spain",
        "arrival": "2021-12-17",
        "departure": "2021-12-19",
        "trip": "Andalusia",
    },
    {
        "city": "Berlin",
        "country": "Germany",
        "arrival": "2021-12-19",
        "departure": "2022-02-04",
        "trip": "",
    },
    {
        "city": "Telnice",
        "country": "Czech Republic",
        "arrival": "2022-02-04",
        "departure": "2022-02-06",
        "trip": "Ski 2",
    },
    {
        "city": "Berlin",
        "country": "Germany",
        "arrival": "2022-02-06",
        "departure": "2022-02-19",
        "trip": "",
    },
    {
        "city": "Budapest",
        "country": "Hungary",
        "arrival": "2022-02-19",
        "departure": "2022-02-22",
        "trip": "Budapest 2022",
    },
    {
        "city": "Berlin",
        "country": "Germany",
        "arrival": "2022-02-22",
        "departure": "2022-03-10",
        "trip": "",
    },
    {
        "city": "São Paulo",
        "country": "Brazil",
        "arrival": "2022-03-11",
        "departure": "2022-03-12",
        "trip": "",
    },
    {
        "city": "Itanhaém",
        "country": "Brazil",
        "arrival": "2022-03-12",
        "departure": "2022-03-13",
        "trip": "",
    },
    {
        "city": "São Paulo",
        "country": "Brazil",
        "arrival": "2022-03-13",
        "departure": "2022-03-23",
        "trip": "",
    },
    {
        "city": "Florianópolis",
        "country": "Brazil",
        "arrival": "2022-03-23",
        "departure": "2022-03-27",
        "trip": "South",
    },
    {
        "city": "Ciudad del Este",
        "country": "Paraguay",
        "arrival": "2022-03-28",
        "departure": "2022-03-28",
        "trip": "South",
    },
    {
        "city": "Puerto Iguazú",
        "country": "Argentina",
        "arrival": "2022-03-29",
        "departure": "2022-03-29",
        "trip": "South",
    },
    {
        "city": "Foz do Iguaçu",
        "country": "Brazil",
        "arrival": "2022-03-30",
        "departure": "2022-03-30",
        "trip": "South",
    },
    {
        "city": "São Paulo",
        "country": "Brazil",
        "arrival": "2022-03-31",
        "departure": "2022-04-08",
        "trip": "",
    },
    {
        "city": "Belém",
        "country": "Brazil",
        "arrival": "2022-04-08",
        "departure": "2022-04-11",
        "trip": "North",
    },
    {
        "city": "Macapá",
        "country": "Brazil",
        "arrival": "2022-04-12",
        "departure": "2022-04-15",
        "trip": "North",
    },
    {
        "city": "Barreirinhas",
        "country": "Brazil",
        "arrival": "2022-04-17",
        "departure": "2022-04-20",
        "trip": "Lençóis",
    },
    {
        "city": "São Luís",
        "country": "Brazil",
        "arrival": "2022-04-20",
        "departure": "2022-04-22",
        "trip": "Lençóis",
    },
    {
        "city": "Bertioga",
        "country": "Brazil",
        "arrival": "2022-04-23",
        "departure": "2022-04-25",
        "trip": "",
    },
    {
        "city": "São Paulo",
        "country": "Brazil",
        "arrival": "2022-04-25",
        "departure": "2022-04-27",
        "trip": "",
    },
    {
        "city": "Berlin",
        "country": "Germany",
        "arrival": "2022-04-28",
        "departure": "2022-08-09",
        "trip": "",
    },
    {
        "city": "Valencia",
        "country": "Spain",
        "arrival": "2022-08-09",
        "departure": "2022-08-16",
        "trip": "Summer 22",
    },
    {
        "city": "Barcelona",
        "country": "Spain",
        "arrival": "2022-08-17",
        "departure": "2022-08-20",
        "trip": "Summer 22",
    },
    {
        "city": "Aix-en-Provence",
        "country": "France",
        "arrival": "2022-08-21",
        "departure": "2022-08-21",
        "trip": "Summer 22",
    },
    {
        "city": "Moustiers-Sainte-Marie",
        "country": "France",
        "arrival": "2022-08-21",
        "departure": "2022-08-23",
        "trip": "Summer 22",
    },
    {
        "city": "Marseille",
        "country": "France",
        "arrival": "2022-08-23",
        "departure": "2022-08-25",
        "trip": "Summer 22",
    },
    {
        "city": "Berlin",
        "country": "Germany",
        "arrival": "2022-08-25",
        "departure": "2022-09-02",
        "trip": "",
    },
    {
        "city": "Leipig",
        "country": "Germany",
        "arrival": "2022-09-02",
        "departure": "2022-09-04",
        "trip": "Leipig",
    },
    {
        "city": "Berlin",
        "country": "Germany",
        "arrival": "2022-09-04",
        "departure": "2022-09-08",
        "trip": "",
    },
    {
        "city": "Rostock",
        "country": "Germany",
        "arrival": "2022-09-08",
        "departure": "2022-09-11",
        "trip": "Rostock",
    },
    {
        "city": "Berlin",
        "country": "Germany",
        "arrival": "2022-09-11",
        "departure": "2022-12-09",
        "trip": "",
    },
    {
        "city": "Lisbon",
        "country": "Portugal",
        "arrival": "2022-12-09",
        "departure": "2022-12-14",
        "trip": "Forro fest",
    },
    {
        "city": "Berlin",
        "country": "Germany",
        "arrival": "2022-12-14",
        "departure": "2022-12-24",
        "trip": "",
    },
    {
        "city": "Rostock",
        "country": "Germany",
        "arrival": "2022-12-24",
        "departure": "2022-12-26",
        "trip": "",
    },
    {
        "city": "Berlin",
        "country": "Germany",
        "arrival": "2022-12-26",
        "departure": "2023-02-16",
        "trip": "",
    },
    {
        "city": "Rostock",
        "country": "Germany",
        "arrival": "2023-02-16",
        "departure": "2023-02-18",
        "trip": "",
    },
    {
        "city": "Berlin",
        "country": "Germany",
        "arrival": "2023-02-18",
        "departure": "2023-03-29",
        "trip": "",
    },
    {
        "city": "Hurghada",
        "country": "Egypt",
        "arrival": "2023-03-29",
        "departure": "2023-04-07",
        "trip": "Red sea",
    },
    {
        "city": "Berlin",
        "country": "Germany",
        "arrival": "2023-04-07",
        "departure": "2023-04-14",
        "trip": "",
    },
    {
        "city": "Madrid",
        "country": "Spain",
        "arrival": "2023-04-14",
        "departure": "2023-04-20",
        "trip": "Blues Madrid",
    },
    {
        "city": "Toledo",
        "country": "Spain",
        "arrival": "2023-04-17",
        "departure": "2023-04-17",
        "trip": "Blues Madrid",
    },
    {
        "city": "Berlin",
        "country": "Germany",
        "arrival": "2023-04-20",
        "departure": "2023-04-27",
        "trip": "",
    },
    {
        "city": "Bergen",
        "country": "Norway",
        "arrival": "2023-04-27",
        "departure": "2023-04-28",
        "trip": "Norway 23",
    },
    {
        "city": "Haugesund",
        "country": "Norway",
        "arrival": "2023-04-28",
        "departure": "2023-05-02",
        "trip": "Norway 23",
    },
    {
        "city": "Oslo",
        "country": "Norway",
        "arrival": "2023-05-02",
        "departure": "2023-05-02",
        "trip": "Norway 23",
    },
    {
        "city": "Berlin",
        "country": "Germany",
        "arrival": "2023-05-02",
        "departure": "2023-05-12",
        "trip": "",
    },
    {
        "city": "Tours",
        "country": "France",
        "arrival": "2023-05-13",
        "departure": "2023-05-16",
        "trip": "Lea",
    },
    {
        "city": "Paris",
        "country": "France",
        "arrival": "2023-05-16",
        "departure": "2023-05-19",
        "trip": "Lea",
    },
    {
        "city": "Mont Saint-Michel",
        "country": "France",
        "arrival": "2023-05-19",
        "departure": "2023-05-21",
        "trip": "Mont Saint-Michel",
    },
    {
        "city": "Berlin",
        "country": "Germany",
        "arrival": "2023-05-22",
        "departure": "2023-06-17",
        "trip": "",
    },
    {
        "city": "Würzburg",
        "country": "Germany",
        "arrival": "2023-06-17",
        "departure": "2023-06-18",
        "trip": "Würzburg",
    },
    {
        "city": "Berlin",
        "country": "Germany",
        "arrival": "2023-06-18",
        "departure": "2023-06-24",
        "trip": "",
    },
    {
        "city": "Nijmegen",
        "country": "Netherlands",
        "arrival": "2023-06-24",
        "departure": "2023-06-28",
        "trip": "Netherlands",
    },
    {
        "city": "Amsterdam",
        "country": "Netherlands",
        "arrival": "2023-06-28",
        "departure": "2023-06-30",
        "trip": "Netherlands",
    },
    {
        "city": "Dordrecht",
        "country": "Netherlands",
        "arrival": "2023-06-30",
        "departure": "2023-07-01",
        "trip": "Netherlands",
    },
    {
        "city": "Hoeven",
        "country": "Netherlands",
        "arrival": "2023-07-01",
        "departure": "2023-07-02",
        "trip": "Netherlands",
    },
    {
        "city": "Berlin",
        "country": "Germany",
        "arrival": "2023-07-02",
        "departure": "2023-07-18",
        "trip": "",
    },
    {
        "city": "Rostock",
        "country": "Germany",
        "arrival": "2023-07-18",
        "departure": "2023-07-23",
        "trip": "",
    },
    {
        "city": "Berlin",
        "country": "Germany",
        "arrival": "2023-07-23",
        "departure": "",
        "trip": "",
    },
]
