export const plans = [
    { title: "Plan 1", duration: 6, start: "2024-03-14", end: "2024-03-20", cities: ["de", "fr"] }, 
    { title: "Plan 2", duration: 4, start: "2024-02-18", end: "2024-03-22", cities: ["de", "pt"] }, 
    { title: "Plan 3", duration: 9, start: "2024-01-10", end: "2024-01-19", cities: ["de", "hu"] }];
export const trips = [
    {id: 157, title: "Birthday Camping", duration: 6, time_ago: 30, countries: ["de"]},
{id: 156, title: "Casamento Bruno e Inês", duration: 5, time_ago: 21, countries: ["pt"]},
{id: 155, title: "Cape Town 2024", duration: 3, time_ago: 28, countries: ["za"]},
{id: 154, title: "Victoria Falls", duration: 3, time_ago: 21, countries: ["zm", "zw"]},
{id: 153, title: "Zanzibar Islands", duration: 6, time_ago: 17, countries: ["tz"]},
{id: 152, title: "Kenya and Tanzania", duration: 2, time_ago: 6, countries: ["ke", "tz"]},
{id: 151, title: "Nicole's Birthday", duration: 1, time_ago: 5, countries: ["sc", "en"]},
{id: 150, title: "Forró in Hanover", duration: 10, time_ago:  29, countries: ["de"]},
{id: 149, title: "Anniversary in Kos", duration: 9, time_ago: 10, countries: ["gr", "tr"]},
{id: 128, title: "Netherlands tour", duration: 6, time_ago: 2, countries: ["nt"]},
{id: 127, title: "Weekend in Würzburg", duration: 6, time_ago: 18, countries: ["de"]},
{id: 126, title: "Mont Saint-Michel", duration: 5, time_ago: 21, countries: ["fr"]},
{id: 125, title: "Visit Lea and Paris", duration: 5, time_ago: 19, countries: ["fr"]},
{id: 124, title: "Norway 2023", duration: 4, time_ago: 2, countries: ["no"]},
{id: 123, title: "Blues Madrid", duration: 4, time_ago: 20, countries: ["es"]},
{id: 122, title: "Diving in the Red Sea", duration: 3, time_ago: 7, countries: ["eg"]},
{id: 121, title: "Lisbon forró 2022", duration: 12,  time_ago:  14, countries: ["pt"]},
{id: 120, title: "Meeting Nat's family", duration: 9,  time_ago: 11, countries: ["de"]},
{id: 119, title: "First time in Leipzig", duration: 9,  time_ago: 4, countries: ["de"]},
{id: 118, title: "Summer 2022", duration: 8, time_ago: 25, countries: ["es", "fr"]},
{id: 117, title: "Lençóis", duration: 4, time_ago: 22, countries: ["br"]},
{id: 116, title: "Viagem pro Norte", duration: 4,  time_ago: 15, countries: ["br"]},
{id: 115, title: "Floripa e Iguaçu", duration: 3, time_ago: 30, countries: ["br", "ar", "pa"]},
{id: 114, title: "Budapest with Nat", duration: 2, time_ago: 22, countries: ["hu"]},
{id: 113, title: "Ski trip 2", duration:  4, time_ago: 6, countries: ["cz"]},
{id: 112, title: "Andalusia", duration: 12, time_ago:  19, countries: ["es"]},
{id: 111, title: "Forró festival 2021", duration: 12,  time_ago:  13, countries: ["pt"]},
{id: 110, title: "Exploring Guadeloupe", duration: 10, time_ago:  4, countries: ["fr"]},
{id: 109, title: "Sexy Schweiz 2", duration: 10, time_ago: 10, countries: ["de"]},
{id: 108, title: "Estonia with Nat", duration: 9, time_ago: 21, countries: ["ee"]},
{id: 107, title: "Niver em Sardegna", duration: 6, time_ago: 30, countries: ["it"]},
{id: 106, title: "Chapada com a Debs", duration: 3, time_ago: 15, countries: ["br"]} 
]
export const stats = {
        countries: 50,
        cities: 188,        
        trips: 116,
        continents: 4,
        total_duration: 1279
    }
export const countries = [
	{
		"id" : 2,
		"name" : "Albania",
		"visited" : 1,
		"need_visa" : 0,
		"lat" : 41.153332,
		"lon" : 20.168331,
		"continent" : "Europe",
		"currency" : "ALL",
		"area_code" : "355",
		"capital" : "Tirana",
		"iso_code" : "al",
		"language" : "sq"
	},
	{
		"id" : 8,
		"name" : "Argentina",
		"visited" : 1,
		"need_visa" : 0,
		"lat" : -38.416097,
		"lon" : -63.616672,
		"continent" : "Americas",
		"currency" : "ARS",
		"area_code" : "54",
		"capital" : "Buenos Aires",
		"iso_code" : "ar",
		"language" : "es"
	},
	{
		"id" : 11,
		"name" : "Austria",
		"visited" : 1,
		"need_visa" : 0,
		"lat" : 47.516231,
		"lon" : 14.550072,
		"continent" : "Europe",
		"currency" : "EUR",
		"area_code" : "43",
		"capital" : "Vienna",
		"iso_code" : "at",
		"language" : "de"
	},
	{
		"id" : 18,
		"name" : "Belgium",
		"visited" : 1,
		"need_visa" : 0,
		"lat" : 50.503887,
		"lon" : 4.469936,
		"continent" : "Europe",
		"currency" : "EUR",
		"area_code" : "32",
		"capital" : "Brussels",
		"iso_code" : "be",
		"language" : "fr"
	},
	{
		"id" : 23,
		"name" : "Bosnia and Herzegovina",
		"visited" : 1,
		"need_visa" : 0,
		"lat" : 43.915886,
		"lon" : 17.679076,
		"continent" : "Europe",
		"currency" : "BAM",
		"area_code" : "387",
		"capital" : "Sarajevo",
		"iso_code" : "ba",
		"language" : "bs"
	},
	{
		"id" : 25,
		"name" : "Brazil",
		"visited" : 1,
		"need_visa" : 0,
		"lat" : -14.235004,
		"lon" : -51.92528,
		"continent" : "Americas",
		"currency" : "BRL",
		"area_code" : "55",
		"capital" : "Brasilia",
		"iso_code" : "br",
		"language" : "pt"
	},
	{
		"id" : 27,
		"name" : "Bulgaria",
		"visited" : 1,
		"need_visa" : 0,
		"lat" : 42.733883,
		"lon" : 25.48583,
		"continent" : "Europe",
		"currency" : "BGN",
		"area_code" : "359",
		"capital" : "Sofia",
		"iso_code" : "bg",
		"language" : "bg"
	},
	{
		"id" : 47,
		"name" : "Czech Republic",
		"visited" : 1,
		"need_visa" : 0,
		"lat" : 49.817492,
		"lon" : 15.472962,
		"continent" : "Europe",
		"currency" : "CZK",
		"area_code" : "420",
		"capital" : "Prague",
		"iso_code" : "cz",
		"language" : "cs"
	},
	{
		"id" : 48,
		"name" : "Denmark",
		"visited" : 1,
		"need_visa" : 0,
		"lat" : 56.26392,
		"lon" : 9.501785,
		"continent" : "Europe",
		"currency" : "DKK",
		"area_code" : "45",
		"capital" : "Copenagen",
		"iso_code" : "dk",
		"language" : "da"
	},
	{
		"id" : 53,
		"name" : "Egypt",
		"visited" : 1,
		"need_visa" : 1,
		"lat" : 26.820553,
		"lon" : 30.802498,
		"continent" : "Africa",
		"currency" : "EGP",
		"area_code" : "20",
		"capital" : "Cairo",
		"iso_code" : "eg",
		"language" : "ar"
	},
	{
		"id" : 55,
		"name" : "England",
		"visited" : 1,
		"need_visa" : 0,
		"lat" : 52.355518000000004,
		"lon" : -1.17432,
		"continent" : "Europe",
		"currency" : "GBP",
		"area_code" : "44",
		"capital" : "London",
		"iso_code" : "gb-eng",
		"language" : "en"
	},
	{
		"id" : 58,
		"name" : "Estonia",
		"visited" : 1,
		"need_visa" : 0,
		"lat" : 58.595272,
		"lon" : 25.013607,
		"continent" : "Europe",
		"currency" : "EUR",
		"area_code" : "372",
		"capital" : "Tallinn",
		"iso_code" : "ee",
		"language" : "et"
	},
	{
		"id" : 61,
		"name" : "Finland",
		"visited" : 1,
		"need_visa" : 0,
		"lat" : 61.92411,
		"lon" : 25.748151,
		"continent" : "Europe",
		"currency" : "EUR",
		"area_code" : "358",
		"capital" : "Helsinki",
		"iso_code" : "fi",
		"language" : "fi"
	},
	{
		"id" : 62,
		"name" : "France",
		"visited" : 1,
		"need_visa" : 0,
		"lat" : 46.227638,
		"lon" : 2.213749,
		"continent" : "Europe",
		"currency" : "EUR",
		"area_code" : "33",
		"capital" : "Paris",
		"iso_code" : "fr",
		"language" : "fr"
	},
	{
		"id" : 65,
		"name" : "Georgia",
		"visited" : 1,
		"need_visa" : 0,
		"lat" : 42.315407,
		"lon" : 43.356892,
		"continent" : "Asia",
		"currency" : "GEL",
		"area_code" : "995",
		"capital" : "Tbilisi",
		"iso_code" : "ge",
		"language" : "ka"
	},
	{
		"id" : 66,
		"name" : "Germany",
		"visited" : 1,
		"need_visa" : 0,
		"lat" : 51.165691,
		"lon" : 10.451526,
		"continent" : "Europe",
		"currency" : "EUR",
		"area_code" : "49",
		"capital" : "Berlin",
		"iso_code" : "de",
		"language" : "de"
	},
	{
		"id" : 68,
		"name" : "Greece",
		"visited" : 1,
		"need_visa" : 0,
		"lat" : 39.074208,
		"lon" : 21.824312,
		"continent" : "Europe",
		"currency" : "EUR",
		"area_code" : "30",
		"capital" : "Athens",
		"iso_code" : "gr",
		"language" : "el"
	},
	{
		"id" : 76,
		"name" : "Hungary",
		"visited" : 1,
		"need_visa" : 0,
		"lat" : 47.162494,
		"lon" : 19.503304,
		"continent" : "Europe",
		"currency" : "HUF",
		"area_code" : "36",
		"capital" : "Budapest",
		"iso_code" : "hu",
		"language" : "hu"
	},
	{
		"id" : 77,
		"name" : "Iceland",
		"visited" : 1,
		"need_visa" : 0,
		"lat" : 64.963051,
		"lon" : -19.020835,
		"continent" : "Europe",
		"currency" : "ISK",
		"area_code" : "354",
		"capital" : "Reykjavík",
		"iso_code" : "is",
		"language" : "is"
	},
	{
		"id" : 82,
		"name" : "Ireland",
		"visited" : 1,
		"need_visa" : 0,
		"lat" : 53.41291,
		"lon" : -8.24389,
		"continent" : "Europe",
		"currency" : "EUR",
		"area_code" : "353",
		"capital" : "Dublin",
		"iso_code" : "ie",
		"language" : "en"
	},
	{
		"id" : 84,
		"name" : "Italy",
		"visited" : 1,
		"need_visa" : 0,
		"lat" : 41.87194,
		"lon" : 12.56738,
		"continent" : "Europe",
		"currency" : "EUR",
		"area_code" : "39",
		"capital" : "Rome",
		"iso_code" : "it",
		"language" : "it"
	},
	{
		"id" : 89,
		"name" : "Kenya",
		"visited" : 1,
		"need_visa" : 1,
		"lat" : -0.023559,
		"lon" : 37.906193,
		"continent" : "Africa",
		"currency" : "KES",
		"area_code" : "254",
		"capital" : "Nairobi",
		"iso_code" : "ke",
		"language" : "sw"
	},
	{
		"id" : 95,
		"name" : "Latvia",
		"visited" : 1,
		"need_visa" : 0,
		"lat" : 56.879635,
		"lon" : 24.603189,
		"continent" : "Europe",
		"currency" : "EUR",
		"area_code" : "371",
		"capital" : "Riga",
		"iso_code" : "lv",
		"language" : "lv"
	},
	{
		"id" : 102,
		"name" : "Luxembourg",
		"visited" : 1,
		"need_visa" : 0,
		"lat" : 49.815273,
		"lon" : 6.129583,
		"continent" : "Europe",
		"currency" : "EUR",
		"area_code" : "352",
		"capital" : "Luxembourg",
		"iso_code" : "lu",
		"language" : "lb"
	},
	{
		"id" : 103,
		"name" : "Macedonia",
		"visited" : 1,
		"need_visa" : 0,
		"lat" : 41.608635,
		"lon" : 21.745275,
		"continent" : "Europe",
		"currency" : "MKD",
		"area_code" : "389",
		"capital" : "Skopje",
		"iso_code" : "mk",
		"language" : "mk"
	},
	{
		"id" : 112,
		"name" : "Mexico",
		"visited" : 1,
		"need_visa" : 0,
		"lat" : 23.634501,
		"lon" : -102.552784,
		"continent" : "Americas",
		"currency" : "MXN",
		"area_code" : "52",
		"capital" : "Mexico City",
		"iso_code" : "mx",
		"language" : "es"
	},
	{
		"id" : 117,
		"name" : "Montenegro",
		"visited" : 1,
		"need_visa" : 0,
		"lat" : 42.708678,
		"lon" : 19.37439,
		"continent" : "Europe",
		"currency" : "EUR",
		"area_code" : "382",
		"capital" : "Podgorica",
		"iso_code" : "me",
		"language" : "cnr"
	},
	{
		"id" : 118,
		"name" : "Morocco",
		"visited" : 1,
		"need_visa" : 0,
		"lat" : 31.791702,
		"lon" : -7.09262,
		"continent" : "Africa",
		"currency" : "MAD",
		"area_code" : "212",
		"capital" : "Rabat",
		"iso_code" : "ma",
		"language" : "ar"
	},
	{
		"id" : 124,
		"name" : "Netherlands",
		"visited" : 1,
		"need_visa" : 0,
		"lat" : 52.132633,
		"lon" : 5.291266,
		"continent" : "Europe",
		"currency" : "EUR",
		"area_code" : "31",
		"capital" : "Amsterdam",
		"iso_code" : "nl",
		"language" : "nl"
	},
	{
		"id" : 130,
		"name" : "Northern Ireland",
		"visited" : 1,
		"need_visa" : 0,
		"lat" : 54.787715,
		"lon" : -6.492314,
		"continent" : "Europe",
		"currency" : "GBP",
		"area_code" : "44",
		"capital" : "Belfast",
		"iso_code" : "gb-nir",
		"language" : "en"
	},
	{
		"id" : 131,
		"name" : "Norway",
		"visited" : 1,
		"need_visa" : 0,
		"lat" : 60.472024,
		"lon" : 8.468946,
		"continent" : "Europe",
		"currency" : "NOK",
		"area_code" : "47",
		"capital" : "Oslo",
		"iso_code" : "no",
		"language" : "no"
	},
	{
		"id" : 138,
		"name" : "Paraguay",
		"visited" : 1,
		"need_visa" : 0,
		"lat" : -23.442503,
		"lon" : -58.443832,
		"continent" : "Americas",
		"currency" : "PYG",
		"area_code" : "595",
		"capital" : "Asunción",
		"iso_code" : "py",
		"language" : "es"
	},
	{
		"id" : 141,
		"name" : "Poland",
		"visited" : 1,
		"need_visa" : 0,
		"lat" : 51.919438,
		"lon" : 19.145136,
		"continent" : "Europe",
		"currency" : "PLN",
		"area_code" : "48",
		"capital" : "Warsaw",
		"iso_code" : "pl",
		"language" : "pl"
	},
	{
		"id" : 142,
		"name" : "Portugal",
		"visited" : 1,
		"need_visa" : 0,
		"lat" : 39.399872,
		"lon" : -8.224454,
		"continent" : "Europe",
		"currency" : "EUR",
		"area_code" : "351",
		"capital" : "Lisbon",
		"iso_code" : "pt",
		"language" : "pt"
	},
	{
		"id" : 144,
		"name" : "Romania",
		"visited" : 1,
		"need_visa" : 0,
		"lat" : 45.943161,
		"lon" : 24.96676,
		"continent" : "Europe",
		"currency" : "RON",
		"area_code" : "40",
		"capital" : "Bucharest",
		"iso_code" : "ro",
		"language" : "ro"
	},
	{
		"id" : 145,
		"name" : "Russia",
		"visited" : 1,
		"need_visa" : 0,
		"lat" : 61.52401,
		"lon" : 105.318756,
		"continent" : "Europe",
		"currency" : "RUB",
		"area_code" : "7",
		"capital" : "Moscow",
		"iso_code" : "ru",
		"language" : "ru"
	},
	{
		"id" : 152,
		"name" : "Scotland",
		"visited" : 1,
		"need_visa" : 0,
		"lat" : 56.490671,
		"lon" : -4.202646,
		"continent" : "Europe",
		"currency" : "GBP",
		"area_code" : "44",
		"capital" : "Edinburgh",
		"iso_code" : "gb-sct",
		"language" : "en"
	},
	{
		"id" : 154,
		"name" : "Serbia",
		"visited" : 1,
		"need_visa" : 0,
		"lat" : 44.016521,
		"lon" : 21.005859,
		"continent" : "Europe",
		"currency" : "CSD",
		"area_code" : "381",
		"capital" : "Belgrade",
		"iso_code" : "rs",
		"language" : "sr"
	},
	{
		"id" : 161,
		"name" : "South Africa",
		"visited" : 1,
		"need_visa" : 0,
		"lat" : -30.559482,
		"lon" : 22.937506,
		"continent" : "Africa",
		"currency" : "ZAR",
		"area_code" : "27",
		"capital" : "Pretoria",
		"iso_code" : "za",
		"language" : "af"
	},
	{
		"id" : 163,
		"name" : "Spain",
		"visited" : 1,
		"need_visa" : 0,
		"lat" : 40.463667,
		"lon" : -3.74922,
		"continent" : "Europe",
		"currency" : "EUR",
		"area_code" : "34",
		"capital" : "Madrid",
		"iso_code" : "es",
		"language" : "es"
	},
	{
		"id" : 167,
		"name" : "Sweden",
		"visited" : 1,
		"need_visa" : 0,
		"lat" : 60.128161,
		"lon" : 18.643501,
		"continent" : "Europe",
		"currency" : "SEK",
		"area_code" : "46",
		"capital" : "Stockholm",
		"iso_code" : "se",
		"language" : "sv"
	},
	{
		"id" : 168,
		"name" : "Switzerland",
		"visited" : 1,
		"need_visa" : 0,
		"lat" : 46.818188,
		"lon" : 8.227512,
		"continent" : "Europe",
		"currency" : "CHF",
		"area_code" : "41",
		"capital" : "Bern",
		"iso_code" : "ch",
		"language" : "de"
	},
	{
		"id" : 172,
		"name" : "Tanzania",
		"visited" : 1,
		"need_visa" : 1,
		"lat" : -6.369028,
		"lon" : 34.888822,
		"continent" : "Africa",
		"currency" : "TZS",
		"area_code" : "255",
		"capital" : "Dodoma",
		"iso_code" : "tz",
		"language" : "sw"
	},
	{
		"id" : 178,
		"name" : "Turkey",
		"visited" : 1,
		"need_visa" : 0,
		"lat" : 38.963745,
		"lon" : 35.243322,
		"continent" : "Asia",
		"currency" : "TRY",
		"area_code" : "90",
		"capital" : "Ankara",
		"iso_code" : "tr",
		"language" : "tr"
	},
	{
		"id" : 182,
		"name" : "Ukraine",
		"visited" : 1,
		"need_visa" : 0,
		"lat" : 48.379433,
		"lon" : 31.16558,
		"continent" : "Europe",
		"currency" : "UAH",
		"area_code" : "380",
		"capital" : "Kiev",
		"iso_code" : "ua",
		"language" : "uk"
	},
	{
		"id" : 184,
		"name" : "United States",
		"visited" : 1,
		"need_visa" : 1,
		"lat" : 37.09024,
		"lon" : -95.712891,
		"continent" : "Americas",
		"currency" : "USD",
		"area_code" : "1",
		"capital" : "Washington D.C.",
		"iso_code" : "us",
		"language" : "en"
	},
	{
		"id" : 192,
		"name" : "Zambia",
		"visited" : 1,
		"need_visa" : 1,
		"lat" : -13.133897,
		"lon" : 27.849332,
		"continent" : "Africa",
		"currency" : "ZMW",
		"area_code" : "260",
		"capital" : "Lusaka",
		"iso_code" : "zm",
		"language" : "en"
	},
	{
		"id" : 193,
		"name" : "Zimbabwe",
		"visited" : 1,
		"need_visa" : 1,
		"lat" : -19.015438,
		"lon" : 29.154857,
		"continent" : "Africa",
		"currency" : "ZWD",
		"area_code" : "263",
		"capital" : "Harare",
		"iso_code" : "zw",
		"language" : "en"
	},
	{
		"id" : 194,
		"name" : "Guadeloupe",
		"visited" : 1,
		"need_visa" : 0,
		"lat" : 16.173094,
		"lon" : -61.4054,
		"continent" : "Europe",
		"currency" : "EUR",
		"area_code" : "590",
		"capital" : "Basse-Terre",
		"iso_code" : "gp",
		"language" : "fr"
	},
	{
		"id" : 195,
		"name" : "Vatican",
		"visited" : 1,
		"need_visa" : 0,
		"lat" : 41.903879,
		"lon" : 12.452083,
		"continent" : "Europe",
		"currency" : "EUR",
		"area_code" : "379",
		"capital" : "Vatican City",
		"iso_code" : "va",
		"language" : "it"
	}
]
export const cities = {countries: 11}
export const stops = {countries: 11}